// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Apt.Inputs
{

    public sealed class SourceArgs : global::Pulumi.ResourceArgs
    {
        [Input("URIs", required: true)]
        private InputList<string>? _URIs;
        public InputList<string> URIs
        {
            get => _URIs ?? (_URIs = new InputList<string>());
            set => _URIs = value;
        }

        [Input("allowDowngradeToInsecure")]
        public Input<bool>? AllowDowngradeToInsecure { get; set; }

        [Input("allowInsecure")]
        public Input<bool>? AllowInsecure { get; set; }

        [Input("allowWeak")]
        public Input<bool>? AllowWeak { get; set; }

        [Input("architectures")]
        private InputList<string>? _architectures;
        public InputList<string> Architectures
        {
            get => _architectures ?? (_architectures = new InputList<string>());
            set => _architectures = value;
        }

        [Input("checkDate")]
        public Input<bool>? CheckDate { get; set; }

        [Input("checkValidUntil")]
        public Input<bool>? CheckValidUntil { get; set; }

        [Input("components", required: true)]
        private InputList<string>? _components;
        public InputList<string> Components
        {
            get => _components ?? (_components = new InputList<string>());
            set => _components = value;
        }

        [Input("dateMaxFuture")]
        public Input<int>? DateMaxFuture { get; set; }

        [Input("extraLines")]
        private InputList<string>? _extraLines;
        public InputList<string> ExtraLines
        {
            get => _extraLines ?? (_extraLines = new InputList<string>());
            set => _extraLines = value;
        }

        [Input("inReleasePath")]
        public Input<string>? InReleasePath { get; set; }

        [Input("signedBy")]
        public Input<Inputs.SignedByArgs>? SignedBy { get; set; }

        [Input("snapshot")]
        public Input<string>? Snapshot { get; set; }

        [Input("suites", required: true)]
        private InputList<string>? _suites;
        public InputList<string> Suites
        {
            get => _suites ?? (_suites = new InputList<string>());
            set => _suites = value;
        }

        [Input("trusted")]
        public Input<bool>? Trusted { get; set; }

        [Input("types", required: true)]
        private InputList<string>? _types;
        public InputList<string> Types
        {
            get => _types ?? (_types = new InputList<string>());
            set => _types = value;
        }

        [Input("validUntilMax")]
        public Input<int>? ValidUntilMax { get; set; }

        [Input("validUntilMin")]
        public Input<int>? ValidUntilMin { get; set; }

        public SourceArgs()
        {
        }
        public static new SourceArgs Empty => new SourceArgs();
    }
}
