# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._enums import *

__all__ = [
    'Flags',
    'KeyPairs',
    'Metrics',
    'ShutdownPolicy',
    'StartupPolicy',
    'TimeoutConfig',
]

@pulumi.output_type
class Flags(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "noWaitForVoteToStartLeader":
            suggest = "no_wait_for_vote_to_start_leader"
        elif key == "rpcBindAddress":
            suggest = "rpc_bind_address"
        elif key == "rpcPort":
            suggest = "rpc_port"
        elif key == "walRecoveryMode":
            suggest = "wal_recovery_mode"
        elif key == "accountIndex":
            suggest = "account_index"
        elif key == "accountIndexExcludeKey":
            suggest = "account_index_exclude_key"
        elif key == "accountIndexIncludeKey":
            suggest = "account_index_include_key"
        elif key == "accountShrinkPath":
            suggest = "account_shrink_path"
        elif key == "accountsDbCacheLimitMb":
            suggest = "accounts_db_cache_limit_mb"
        elif key == "accountsDbTestHashCalculation":
            suggest = "accounts_db_test_hash_calculation"
        elif key == "accountsHashCachePath":
            suggest = "accounts_hash_cache_path"
        elif key == "accountsIndexBins":
            suggest = "accounts_index_bins"
        elif key == "accountsIndexPath":
            suggest = "accounts_index_path"
        elif key == "accountsIndexScanResultsLimitMb":
            suggest = "accounts_index_scan_results_limit_mb"
        elif key == "accountsShrinkOptimizeTotalSpace":
            suggest = "accounts_shrink_optimize_total_space"
        elif key == "accountsShrinkRatio":
            suggest = "accounts_shrink_ratio"
        elif key == "allowPrivateAddr":
            suggest = "allow_private_addr"
        elif key == "authorizedVoter":
            suggest = "authorized_voter"
        elif key == "bindAddress":
            suggest = "bind_address"
        elif key == "blockProductionMethod":
            suggest = "block_production_method"
        elif key == "blockVerificationMethod":
            suggest = "block_verification_method"
        elif key == "checkVoteAccount":
            suggest = "check_vote_account"
        elif key == "contactDebugInterval":
            suggest = "contact_debug_interval"
        elif key == "debugKey":
            suggest = "debug_key"
        elif key == "devHaltAtSlot":
            suggest = "dev_halt_at_slot"
        elif key == "disableBankingTrace":
            suggest = "disable_banking_trace"
        elif key == "dynamicPortRange":
            suggest = "dynamic_port_range"
        elif key == "enableBankingTrace":
            suggest = "enable_banking_trace"
        elif key == "enableBigtableLedgerUpload":
            suggest = "enable_bigtable_ledger_upload"
        elif key == "enableExtendedTxMetadataStorage":
            suggest = "enable_extended_tx_metadata_storage"
        elif key == "enableRpcBigtableLedgerStorage":
            suggest = "enable_rpc_bigtable_ledger_storage"
        elif key == "enableRpcTransactionHistory":
            suggest = "enable_rpc_transaction_history"
        elif key == "entryPoint":
            suggest = "entry_point"
        elif key == "etcdCacertFile":
            suggest = "etcd_cacert_file"
        elif key == "etcdCertFile":
            suggest = "etcd_cert_file"
        elif key == "etcdDomainName":
            suggest = "etcd_domain_name"
        elif key == "etcdEndpoint":
            suggest = "etcd_endpoint"
        elif key == "etcdKeyFile":
            suggest = "etcd_key_file"
        elif key == "expectedBankHash":
            suggest = "expected_bank_hash"
        elif key == "expectedGenesisHash":
            suggest = "expected_genesis_hash"
        elif key == "expectedShredVersion":
            suggest = "expected_shred_version"
        elif key == "extraFlags":
            suggest = "extra_flags"
        elif key == "fullRpcAPI":
            suggest = "full_rpc_api"
        elif key == "fullSnapshotArchivePath":
            suggest = "full_snapshot_archive_path"
        elif key == "fullSnapshotIntervalSlots":
            suggest = "full_snapshot_interval_slots"
        elif key == "geyserPluginAlwaysEnabled":
            suggest = "geyser_plugin_always_enabled"
        elif key == "geyserPluginConfig":
            suggest = "geyser_plugin_config"
        elif key == "gossipHost":
            suggest = "gossip_host"
        elif key == "gossipPort":
            suggest = "gossip_port"
        elif key == "gossipValidator":
            suggest = "gossip_validator"
        elif key == "hardFork":
            suggest = "hard_fork"
        elif key == "healthCheckSlotDistance":
            suggest = "health_check_slot_distance"
        elif key == "incrementalSnapshotArchivePath":
            suggest = "incremental_snapshot_archive_path"
        elif key == "initCompleteFile":
            suggest = "init_complete_file"
        elif key == "knownValidator":
            suggest = "known_validator"
        elif key == "limitLedgerSize":
            suggest = "limit_ledger_size"
        elif key == "logMessagesBytesLimit":
            suggest = "log_messages_bytes_limit"
        elif key == "maxGenesisArchiveUnpackedSize":
            suggest = "max_genesis_archive_unpacked_size"
        elif key == "maximumFullSnapshotsToRetain":
            suggest = "maximum_full_snapshots_to_retain"
        elif key == "maximumIncrementalSnapshotsToRetain":
            suggest = "maximum_incremental_snapshots_to_retain"
        elif key == "maximumLocalSnapshotAge":
            suggest = "maximum_local_snapshot_age"
        elif key == "maximumSnapshotDownloadAbort":
            suggest = "maximum_snapshot_download_abort"
        elif key == "minimalSnapshotDownloadSpeed":
            suggest = "minimal_snapshot_download_speed"
        elif key == "noGenesisFetch":
            suggest = "no_genesis_fetch"
        elif key == "noIncrementalSnapshots":
            suggest = "no_incremental_snapshots"
        elif key == "noSnapshotFetch":
            suggest = "no_snapshot_fetch"
        elif key == "noVoting":
            suggest = "no_voting"
        elif key == "onlyKnownRPC":
            suggest = "only_known_rpc"
        elif key == "privateRPC":
            suggest = "private_rpc"
        elif key == "publicRpcAddress":
            suggest = "public_rpc_address"
        elif key == "publicTpuAddress":
            suggest = "public_tpu_address"
        elif key == "publicTpuForwardsAddress":
            suggest = "public_tpu_forwards_address"
        elif key == "repairValidator":
            suggest = "repair_validator"
        elif key == "requireTower":
            suggest = "require_tower"
        elif key == "restrictedRepairOnlyMode":
            suggest = "restricted_repair_only_mode"
        elif key == "rocksdbFifoShredStorageSize":
            suggest = "rocksdb_fifo_shred_storage_size"
        elif key == "rocksdbShredCompaction":
            suggest = "rocksdb_shred_compaction"
        elif key == "rpcBigtableAppProfileId":
            suggest = "rpc_bigtable_app_profile_id"
        elif key == "rpcBigtableInstanceName":
            suggest = "rpc_bigtable_instance_name"
        elif key == "rpcBigtableMaxMessageSize":
            suggest = "rpc_bigtable_max_message_size"
        elif key == "rpcBigtableTimeout":
            suggest = "rpc_bigtable_timeout"
        elif key == "rpcFaucetAddress":
            suggest = "rpc_faucet_address"
        elif key == "rpcMaxMultipleAccounts":
            suggest = "rpc_max_multiple_accounts"
        elif key == "rpcMaxRequestBodySize":
            suggest = "rpc_max_request_body_size"
        elif key == "rpcNicenessAdjustment":
            suggest = "rpc_niceness_adjustment"
        elif key == "rpcPubsubEnableBlockSubscription":
            suggest = "rpc_pubsub_enable_block_subscription"
        elif key == "rpcPubsubEnableVoteSubscription":
            suggest = "rpc_pubsub_enable_vote_subscription"
        elif key == "rpcPubsubMaxActiveSubscriptions":
            suggest = "rpc_pubsub_max_active_subscriptions"
        elif key == "rpcPubsubNotificationThreads":
            suggest = "rpc_pubsub_notification_threads"
        elif key == "rpcPubsubQueueCapacityBytes":
            suggest = "rpc_pubsub_queue_capacity_bytes"
        elif key == "rpcPubsubQueueCapacityItems":
            suggest = "rpc_pubsub_queue_capacity_items"
        elif key == "rpcPubsubWorkerThreads":
            suggest = "rpc_pubsub_worker_threads"
        elif key == "rpcScanAndFixRoots":
            suggest = "rpc_scan_and_fix_roots"
        elif key == "rpcSendLeaderCount":
            suggest = "rpc_send_leader_count"
        elif key == "rpcSendRetryMs":
            suggest = "rpc_send_retry_ms"
        elif key == "rpcSendServiceMaxRetries":
            suggest = "rpc_send_service_max_retries"
        elif key == "rpcSendTransactionAlsoLeader":
            suggest = "rpc_send_transaction_also_leader"
        elif key == "rpcSendTransactionRetryPoolMaxSize":
            suggest = "rpc_send_transaction_retry_pool_max_size"
        elif key == "rpcSendTransactionTpuPeer":
            suggest = "rpc_send_transaction_tpu_peer"
        elif key == "rpcThreads":
            suggest = "rpc_threads"
        elif key == "skipPreflightHealthCheck":
            suggest = "skip_preflight_health_check"
        elif key == "skipSeedPhraseValidation":
            suggest = "skip_seed_phrase_validation"
        elif key == "skipStartupLedgerVerification":
            suggest = "skip_startup_ledger_verification"
        elif key == "snapshotArchiveFormat":
            suggest = "snapshot_archive_format"
        elif key == "snapshotIntervalSlots":
            suggest = "snapshot_interval_slots"
        elif key == "snapshotPackagerNicenessAdjustment":
            suggest = "snapshot_packager_niceness_adjustment"
        elif key == "snapshotVersion":
            suggest = "snapshot_version"
        elif key == "stakedNodesOverrides":
            suggest = "staked_nodes_overrides"
        elif key == "towerStorage":
            suggest = "tower_storage"
        elif key == "tpuCoalesceMs":
            suggest = "tpu_coalesce_ms"
        elif key == "tpuConnectionPoolSize":
            suggest = "tpu_connection_pool_size"
        elif key == "tpuDisableQuic":
            suggest = "tpu_disable_quic"
        elif key == "tpuEnableUdp":
            suggest = "tpu_enable_udp"
        elif key == "tvuReceiveThreads":
            suggest = "tvu_receive_threads"
        elif key == "unifiedSchedulerHandlerThreads":
            suggest = "unified_scheduler_handler_threads"
        elif key == "useSnapshotArchivesAtStartup":
            suggest = "use_snapshot_archives_at_startup"
        elif key == "waitForSupermajority":
            suggest = "wait_for_supermajority"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in Flags. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        Flags.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        Flags.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 no_wait_for_vote_to_start_leader: _builtins.bool,
                 rpc_bind_address: _builtins.str,
                 rpc_port: _builtins.int,
                 wal_recovery_mode: _builtins.str,
                 account_index: Optional[Sequence[_builtins.str]] = None,
                 account_index_exclude_key: Optional[Sequence[_builtins.str]] = None,
                 account_index_include_key: Optional[Sequence[_builtins.str]] = None,
                 account_shrink_path: Optional[Sequence[_builtins.str]] = None,
                 accounts_db_cache_limit_mb: Optional[_builtins.int] = None,
                 accounts_db_test_hash_calculation: Optional[_builtins.bool] = None,
                 accounts_hash_cache_path: Optional[_builtins.str] = None,
                 accounts_index_bins: Optional[_builtins.int] = None,
                 accounts_index_path: Optional[Sequence[_builtins.str]] = None,
                 accounts_index_scan_results_limit_mb: Optional[_builtins.int] = None,
                 accounts_shrink_optimize_total_space: Optional[_builtins.bool] = None,
                 accounts_shrink_ratio: Optional[_builtins.str] = None,
                 allow_private_addr: Optional[_builtins.bool] = None,
                 authorized_voter: Optional[Sequence[_builtins.str]] = None,
                 bind_address: Optional[_builtins.str] = None,
                 block_production_method: Optional[_builtins.str] = None,
                 block_verification_method: Optional[_builtins.str] = None,
                 check_vote_account: Optional[_builtins.str] = None,
                 contact_debug_interval: Optional[_builtins.int] = None,
                 cuda: Optional[_builtins.bool] = None,
                 debug_key: Optional[Sequence[_builtins.str]] = None,
                 dev_halt_at_slot: Optional[_builtins.int] = None,
                 disable_banking_trace: Optional[_builtins.bool] = None,
                 dynamic_port_range: Optional[_builtins.str] = None,
                 enable_banking_trace: Optional[_builtins.int] = None,
                 enable_bigtable_ledger_upload: Optional[_builtins.bool] = None,
                 enable_extended_tx_metadata_storage: Optional[_builtins.bool] = None,
                 enable_rpc_bigtable_ledger_storage: Optional[_builtins.bool] = None,
                 enable_rpc_transaction_history: Optional[_builtins.bool] = None,
                 entry_point: Optional[Sequence[_builtins.str]] = None,
                 etcd_cacert_file: Optional[_builtins.str] = None,
                 etcd_cert_file: Optional[_builtins.str] = None,
                 etcd_domain_name: Optional[_builtins.str] = None,
                 etcd_endpoint: Optional[Sequence[_builtins.str]] = None,
                 etcd_key_file: Optional[_builtins.str] = None,
                 expected_bank_hash: Optional[_builtins.str] = None,
                 expected_genesis_hash: Optional[_builtins.str] = None,
                 expected_shred_version: Optional[_builtins.int] = None,
                 extra_flags: Optional[Sequence[_builtins.str]] = None,
                 full_rpc_api: Optional[_builtins.bool] = None,
                 full_snapshot_archive_path: Optional[_builtins.str] = None,
                 full_snapshot_interval_slots: Optional[_builtins.int] = None,
                 geyser_plugin_always_enabled: Optional[_builtins.bool] = None,
                 geyser_plugin_config: Optional[Sequence[_builtins.str]] = None,
                 gossip_host: Optional[_builtins.str] = None,
                 gossip_port: Optional[_builtins.int] = None,
                 gossip_validator: Optional[Sequence[_builtins.str]] = None,
                 hard_fork: Optional[Sequence[_builtins.int]] = None,
                 health_check_slot_distance: Optional[_builtins.int] = None,
                 incremental_snapshot_archive_path: Optional[_builtins.str] = None,
                 init_complete_file: Optional[_builtins.str] = None,
                 known_validator: Optional[Sequence[_builtins.str]] = None,
                 limit_ledger_size: Optional[_builtins.int] = None,
                 log: Optional[_builtins.str] = None,
                 log_messages_bytes_limit: Optional[_builtins.int] = None,
                 max_genesis_archive_unpacked_size: Optional[_builtins.int] = None,
                 maximum_full_snapshots_to_retain: Optional[_builtins.int] = None,
                 maximum_incremental_snapshots_to_retain: Optional[_builtins.int] = None,
                 maximum_local_snapshot_age: Optional[_builtins.int] = None,
                 maximum_snapshot_download_abort: Optional[_builtins.int] = None,
                 minimal_snapshot_download_speed: Optional[_builtins.int] = None,
                 no_genesis_fetch: Optional[_builtins.bool] = None,
                 no_incremental_snapshots: Optional[_builtins.bool] = None,
                 no_snapshot_fetch: Optional[_builtins.bool] = None,
                 no_voting: Optional[_builtins.bool] = None,
                 only_known_rpc: Optional[_builtins.bool] = None,
                 private_rpc: Optional[_builtins.bool] = None,
                 public_rpc_address: Optional[_builtins.str] = None,
                 public_tpu_address: Optional[_builtins.str] = None,
                 public_tpu_forwards_address: Optional[_builtins.str] = None,
                 repair_validator: Optional[Sequence[_builtins.str]] = None,
                 require_tower: Optional[_builtins.bool] = None,
                 restricted_repair_only_mode: Optional[_builtins.bool] = None,
                 rocksdb_fifo_shred_storage_size: Optional[_builtins.int] = None,
                 rocksdb_shred_compaction: Optional[_builtins.str] = None,
                 rpc_bigtable_app_profile_id: Optional[_builtins.str] = None,
                 rpc_bigtable_instance_name: Optional[_builtins.str] = None,
                 rpc_bigtable_max_message_size: Optional[_builtins.int] = None,
                 rpc_bigtable_timeout: Optional[_builtins.int] = None,
                 rpc_faucet_address: Optional[_builtins.str] = None,
                 rpc_max_multiple_accounts: Optional[_builtins.int] = None,
                 rpc_max_request_body_size: Optional[_builtins.int] = None,
                 rpc_niceness_adjustment: Optional[_builtins.int] = None,
                 rpc_pubsub_enable_block_subscription: Optional[_builtins.bool] = None,
                 rpc_pubsub_enable_vote_subscription: Optional[_builtins.bool] = None,
                 rpc_pubsub_max_active_subscriptions: Optional[_builtins.int] = None,
                 rpc_pubsub_notification_threads: Optional[_builtins.int] = None,
                 rpc_pubsub_queue_capacity_bytes: Optional[_builtins.int] = None,
                 rpc_pubsub_queue_capacity_items: Optional[_builtins.int] = None,
                 rpc_pubsub_worker_threads: Optional[_builtins.int] = None,
                 rpc_scan_and_fix_roots: Optional[_builtins.bool] = None,
                 rpc_send_leader_count: Optional[_builtins.int] = None,
                 rpc_send_retry_ms: Optional[_builtins.int] = None,
                 rpc_send_service_max_retries: Optional[_builtins.int] = None,
                 rpc_send_transaction_also_leader: Optional[_builtins.bool] = None,
                 rpc_send_transaction_retry_pool_max_size: Optional[_builtins.int] = None,
                 rpc_send_transaction_tpu_peer: Optional[Sequence[_builtins.str]] = None,
                 rpc_threads: Optional[_builtins.int] = None,
                 skip_preflight_health_check: Optional[_builtins.bool] = None,
                 skip_seed_phrase_validation: Optional[_builtins.bool] = None,
                 skip_startup_ledger_verification: Optional[_builtins.bool] = None,
                 snapshot_archive_format: Optional[_builtins.str] = None,
                 snapshot_interval_slots: Optional[_builtins.int] = None,
                 snapshot_packager_niceness_adjustment: Optional[_builtins.int] = None,
                 snapshot_version: Optional[_builtins.str] = None,
                 staked_nodes_overrides: Optional[_builtins.str] = None,
                 tower_storage: Optional[_builtins.str] = None,
                 tpu_coalesce_ms: Optional[_builtins.int] = None,
                 tpu_connection_pool_size: Optional[_builtins.int] = None,
                 tpu_disable_quic: Optional[_builtins.bool] = None,
                 tpu_enable_udp: Optional[_builtins.bool] = None,
                 tvu_receive_threads: Optional[_builtins.int] = None,
                 unified_scheduler_handler_threads: Optional[_builtins.int] = None,
                 use_snapshot_archives_at_startup: Optional[_builtins.str] = None,
                 wait_for_supermajority: Optional[_builtins.int] = None):
        pulumi.set(__self__, "no_wait_for_vote_to_start_leader", no_wait_for_vote_to_start_leader)
        pulumi.set(__self__, "rpc_bind_address", rpc_bind_address)
        pulumi.set(__self__, "rpc_port", rpc_port)
        pulumi.set(__self__, "wal_recovery_mode", wal_recovery_mode)
        if account_index is not None:
            pulumi.set(__self__, "account_index", account_index)
        if account_index_exclude_key is not None:
            pulumi.set(__self__, "account_index_exclude_key", account_index_exclude_key)
        if account_index_include_key is not None:
            pulumi.set(__self__, "account_index_include_key", account_index_include_key)
        if account_shrink_path is not None:
            pulumi.set(__self__, "account_shrink_path", account_shrink_path)
        if accounts_db_cache_limit_mb is not None:
            pulumi.set(__self__, "accounts_db_cache_limit_mb", accounts_db_cache_limit_mb)
        if accounts_db_test_hash_calculation is not None:
            pulumi.set(__self__, "accounts_db_test_hash_calculation", accounts_db_test_hash_calculation)
        if accounts_hash_cache_path is not None:
            pulumi.set(__self__, "accounts_hash_cache_path", accounts_hash_cache_path)
        if accounts_index_bins is not None:
            pulumi.set(__self__, "accounts_index_bins", accounts_index_bins)
        if accounts_index_path is not None:
            pulumi.set(__self__, "accounts_index_path", accounts_index_path)
        if accounts_index_scan_results_limit_mb is not None:
            pulumi.set(__self__, "accounts_index_scan_results_limit_mb", accounts_index_scan_results_limit_mb)
        if accounts_shrink_optimize_total_space is not None:
            pulumi.set(__self__, "accounts_shrink_optimize_total_space", accounts_shrink_optimize_total_space)
        if accounts_shrink_ratio is not None:
            pulumi.set(__self__, "accounts_shrink_ratio", accounts_shrink_ratio)
        if allow_private_addr is not None:
            pulumi.set(__self__, "allow_private_addr", allow_private_addr)
        if authorized_voter is not None:
            pulumi.set(__self__, "authorized_voter", authorized_voter)
        if bind_address is not None:
            pulumi.set(__self__, "bind_address", bind_address)
        if block_production_method is not None:
            pulumi.set(__self__, "block_production_method", block_production_method)
        if block_verification_method is not None:
            pulumi.set(__self__, "block_verification_method", block_verification_method)
        if check_vote_account is not None:
            pulumi.set(__self__, "check_vote_account", check_vote_account)
        if contact_debug_interval is not None:
            pulumi.set(__self__, "contact_debug_interval", contact_debug_interval)
        if cuda is not None:
            pulumi.set(__self__, "cuda", cuda)
        if debug_key is not None:
            pulumi.set(__self__, "debug_key", debug_key)
        if dev_halt_at_slot is not None:
            pulumi.set(__self__, "dev_halt_at_slot", dev_halt_at_slot)
        if disable_banking_trace is not None:
            pulumi.set(__self__, "disable_banking_trace", disable_banking_trace)
        if dynamic_port_range is not None:
            pulumi.set(__self__, "dynamic_port_range", dynamic_port_range)
        if enable_banking_trace is not None:
            pulumi.set(__self__, "enable_banking_trace", enable_banking_trace)
        if enable_bigtable_ledger_upload is not None:
            pulumi.set(__self__, "enable_bigtable_ledger_upload", enable_bigtable_ledger_upload)
        if enable_extended_tx_metadata_storage is not None:
            pulumi.set(__self__, "enable_extended_tx_metadata_storage", enable_extended_tx_metadata_storage)
        if enable_rpc_bigtable_ledger_storage is not None:
            pulumi.set(__self__, "enable_rpc_bigtable_ledger_storage", enable_rpc_bigtable_ledger_storage)
        if enable_rpc_transaction_history is not None:
            pulumi.set(__self__, "enable_rpc_transaction_history", enable_rpc_transaction_history)
        if entry_point is not None:
            pulumi.set(__self__, "entry_point", entry_point)
        if etcd_cacert_file is not None:
            pulumi.set(__self__, "etcd_cacert_file", etcd_cacert_file)
        if etcd_cert_file is not None:
            pulumi.set(__self__, "etcd_cert_file", etcd_cert_file)
        if etcd_domain_name is not None:
            pulumi.set(__self__, "etcd_domain_name", etcd_domain_name)
        if etcd_endpoint is not None:
            pulumi.set(__self__, "etcd_endpoint", etcd_endpoint)
        if etcd_key_file is not None:
            pulumi.set(__self__, "etcd_key_file", etcd_key_file)
        if expected_bank_hash is not None:
            pulumi.set(__self__, "expected_bank_hash", expected_bank_hash)
        if expected_genesis_hash is not None:
            pulumi.set(__self__, "expected_genesis_hash", expected_genesis_hash)
        if expected_shred_version is not None:
            pulumi.set(__self__, "expected_shred_version", expected_shred_version)
        if extra_flags is not None:
            pulumi.set(__self__, "extra_flags", extra_flags)
        if full_rpc_api is not None:
            pulumi.set(__self__, "full_rpc_api", full_rpc_api)
        if full_snapshot_archive_path is not None:
            pulumi.set(__self__, "full_snapshot_archive_path", full_snapshot_archive_path)
        if full_snapshot_interval_slots is not None:
            pulumi.set(__self__, "full_snapshot_interval_slots", full_snapshot_interval_slots)
        if geyser_plugin_always_enabled is not None:
            pulumi.set(__self__, "geyser_plugin_always_enabled", geyser_plugin_always_enabled)
        if geyser_plugin_config is not None:
            pulumi.set(__self__, "geyser_plugin_config", geyser_plugin_config)
        if gossip_host is not None:
            pulumi.set(__self__, "gossip_host", gossip_host)
        if gossip_port is not None:
            pulumi.set(__self__, "gossip_port", gossip_port)
        if gossip_validator is not None:
            pulumi.set(__self__, "gossip_validator", gossip_validator)
        if hard_fork is not None:
            pulumi.set(__self__, "hard_fork", hard_fork)
        if health_check_slot_distance is not None:
            pulumi.set(__self__, "health_check_slot_distance", health_check_slot_distance)
        if incremental_snapshot_archive_path is not None:
            pulumi.set(__self__, "incremental_snapshot_archive_path", incremental_snapshot_archive_path)
        if init_complete_file is not None:
            pulumi.set(__self__, "init_complete_file", init_complete_file)
        if known_validator is not None:
            pulumi.set(__self__, "known_validator", known_validator)
        if limit_ledger_size is not None:
            pulumi.set(__self__, "limit_ledger_size", limit_ledger_size)
        if log is not None:
            pulumi.set(__self__, "log", log)
        if log_messages_bytes_limit is not None:
            pulumi.set(__self__, "log_messages_bytes_limit", log_messages_bytes_limit)
        if max_genesis_archive_unpacked_size is not None:
            pulumi.set(__self__, "max_genesis_archive_unpacked_size", max_genesis_archive_unpacked_size)
        if maximum_full_snapshots_to_retain is not None:
            pulumi.set(__self__, "maximum_full_snapshots_to_retain", maximum_full_snapshots_to_retain)
        if maximum_incremental_snapshots_to_retain is not None:
            pulumi.set(__self__, "maximum_incremental_snapshots_to_retain", maximum_incremental_snapshots_to_retain)
        if maximum_local_snapshot_age is not None:
            pulumi.set(__self__, "maximum_local_snapshot_age", maximum_local_snapshot_age)
        if maximum_snapshot_download_abort is not None:
            pulumi.set(__self__, "maximum_snapshot_download_abort", maximum_snapshot_download_abort)
        if minimal_snapshot_download_speed is not None:
            pulumi.set(__self__, "minimal_snapshot_download_speed", minimal_snapshot_download_speed)
        if no_genesis_fetch is not None:
            pulumi.set(__self__, "no_genesis_fetch", no_genesis_fetch)
        if no_incremental_snapshots is not None:
            pulumi.set(__self__, "no_incremental_snapshots", no_incremental_snapshots)
        if no_snapshot_fetch is not None:
            pulumi.set(__self__, "no_snapshot_fetch", no_snapshot_fetch)
        if no_voting is not None:
            pulumi.set(__self__, "no_voting", no_voting)
        if only_known_rpc is not None:
            pulumi.set(__self__, "only_known_rpc", only_known_rpc)
        if private_rpc is not None:
            pulumi.set(__self__, "private_rpc", private_rpc)
        if public_rpc_address is not None:
            pulumi.set(__self__, "public_rpc_address", public_rpc_address)
        if public_tpu_address is not None:
            pulumi.set(__self__, "public_tpu_address", public_tpu_address)
        if public_tpu_forwards_address is not None:
            pulumi.set(__self__, "public_tpu_forwards_address", public_tpu_forwards_address)
        if repair_validator is not None:
            pulumi.set(__self__, "repair_validator", repair_validator)
        if require_tower is not None:
            pulumi.set(__self__, "require_tower", require_tower)
        if restricted_repair_only_mode is not None:
            pulumi.set(__self__, "restricted_repair_only_mode", restricted_repair_only_mode)
        if rocksdb_fifo_shred_storage_size is not None:
            pulumi.set(__self__, "rocksdb_fifo_shred_storage_size", rocksdb_fifo_shred_storage_size)
        if rocksdb_shred_compaction is not None:
            pulumi.set(__self__, "rocksdb_shred_compaction", rocksdb_shred_compaction)
        if rpc_bigtable_app_profile_id is not None:
            pulumi.set(__self__, "rpc_bigtable_app_profile_id", rpc_bigtable_app_profile_id)
        if rpc_bigtable_instance_name is not None:
            pulumi.set(__self__, "rpc_bigtable_instance_name", rpc_bigtable_instance_name)
        if rpc_bigtable_max_message_size is not None:
            pulumi.set(__self__, "rpc_bigtable_max_message_size", rpc_bigtable_max_message_size)
        if rpc_bigtable_timeout is not None:
            pulumi.set(__self__, "rpc_bigtable_timeout", rpc_bigtable_timeout)
        if rpc_faucet_address is not None:
            pulumi.set(__self__, "rpc_faucet_address", rpc_faucet_address)
        if rpc_max_multiple_accounts is not None:
            pulumi.set(__self__, "rpc_max_multiple_accounts", rpc_max_multiple_accounts)
        if rpc_max_request_body_size is not None:
            pulumi.set(__self__, "rpc_max_request_body_size", rpc_max_request_body_size)
        if rpc_niceness_adjustment is not None:
            pulumi.set(__self__, "rpc_niceness_adjustment", rpc_niceness_adjustment)
        if rpc_pubsub_enable_block_subscription is not None:
            pulumi.set(__self__, "rpc_pubsub_enable_block_subscription", rpc_pubsub_enable_block_subscription)
        if rpc_pubsub_enable_vote_subscription is not None:
            pulumi.set(__self__, "rpc_pubsub_enable_vote_subscription", rpc_pubsub_enable_vote_subscription)
        if rpc_pubsub_max_active_subscriptions is not None:
            pulumi.set(__self__, "rpc_pubsub_max_active_subscriptions", rpc_pubsub_max_active_subscriptions)
        if rpc_pubsub_notification_threads is not None:
            pulumi.set(__self__, "rpc_pubsub_notification_threads", rpc_pubsub_notification_threads)
        if rpc_pubsub_queue_capacity_bytes is not None:
            pulumi.set(__self__, "rpc_pubsub_queue_capacity_bytes", rpc_pubsub_queue_capacity_bytes)
        if rpc_pubsub_queue_capacity_items is not None:
            pulumi.set(__self__, "rpc_pubsub_queue_capacity_items", rpc_pubsub_queue_capacity_items)
        if rpc_pubsub_worker_threads is not None:
            pulumi.set(__self__, "rpc_pubsub_worker_threads", rpc_pubsub_worker_threads)
        if rpc_scan_and_fix_roots is not None:
            pulumi.set(__self__, "rpc_scan_and_fix_roots", rpc_scan_and_fix_roots)
        if rpc_send_leader_count is not None:
            pulumi.set(__self__, "rpc_send_leader_count", rpc_send_leader_count)
        if rpc_send_retry_ms is not None:
            pulumi.set(__self__, "rpc_send_retry_ms", rpc_send_retry_ms)
        if rpc_send_service_max_retries is not None:
            pulumi.set(__self__, "rpc_send_service_max_retries", rpc_send_service_max_retries)
        if rpc_send_transaction_also_leader is not None:
            pulumi.set(__self__, "rpc_send_transaction_also_leader", rpc_send_transaction_also_leader)
        if rpc_send_transaction_retry_pool_max_size is not None:
            pulumi.set(__self__, "rpc_send_transaction_retry_pool_max_size", rpc_send_transaction_retry_pool_max_size)
        if rpc_send_transaction_tpu_peer is not None:
            pulumi.set(__self__, "rpc_send_transaction_tpu_peer", rpc_send_transaction_tpu_peer)
        if rpc_threads is not None:
            pulumi.set(__self__, "rpc_threads", rpc_threads)
        if skip_preflight_health_check is not None:
            pulumi.set(__self__, "skip_preflight_health_check", skip_preflight_health_check)
        if skip_seed_phrase_validation is not None:
            pulumi.set(__self__, "skip_seed_phrase_validation", skip_seed_phrase_validation)
        if skip_startup_ledger_verification is not None:
            pulumi.set(__self__, "skip_startup_ledger_verification", skip_startup_ledger_verification)
        if snapshot_archive_format is not None:
            pulumi.set(__self__, "snapshot_archive_format", snapshot_archive_format)
        if snapshot_interval_slots is not None:
            pulumi.set(__self__, "snapshot_interval_slots", snapshot_interval_slots)
        if snapshot_packager_niceness_adjustment is not None:
            pulumi.set(__self__, "snapshot_packager_niceness_adjustment", snapshot_packager_niceness_adjustment)
        if snapshot_version is not None:
            pulumi.set(__self__, "snapshot_version", snapshot_version)
        if staked_nodes_overrides is not None:
            pulumi.set(__self__, "staked_nodes_overrides", staked_nodes_overrides)
        if tower_storage is not None:
            pulumi.set(__self__, "tower_storage", tower_storage)
        if tpu_coalesce_ms is not None:
            pulumi.set(__self__, "tpu_coalesce_ms", tpu_coalesce_ms)
        if tpu_connection_pool_size is not None:
            pulumi.set(__self__, "tpu_connection_pool_size", tpu_connection_pool_size)
        if tpu_disable_quic is not None:
            pulumi.set(__self__, "tpu_disable_quic", tpu_disable_quic)
        if tpu_enable_udp is not None:
            pulumi.set(__self__, "tpu_enable_udp", tpu_enable_udp)
        if tvu_receive_threads is not None:
            pulumi.set(__self__, "tvu_receive_threads", tvu_receive_threads)
        if unified_scheduler_handler_threads is not None:
            pulumi.set(__self__, "unified_scheduler_handler_threads", unified_scheduler_handler_threads)
        if use_snapshot_archives_at_startup is not None:
            pulumi.set(__self__, "use_snapshot_archives_at_startup", use_snapshot_archives_at_startup)
        if wait_for_supermajority is not None:
            pulumi.set(__self__, "wait_for_supermajority", wait_for_supermajority)

    @_builtins.property
    @pulumi.getter(name="noWaitForVoteToStartLeader")
    def no_wait_for_vote_to_start_leader(self) -> _builtins.bool:
        return pulumi.get(self, "no_wait_for_vote_to_start_leader")

    @_builtins.property
    @pulumi.getter(name="rpcBindAddress")
    def rpc_bind_address(self) -> _builtins.str:
        return pulumi.get(self, "rpc_bind_address")

    @_builtins.property
    @pulumi.getter(name="rpcPort")
    def rpc_port(self) -> _builtins.int:
        return pulumi.get(self, "rpc_port")

    @_builtins.property
    @pulumi.getter(name="walRecoveryMode")
    def wal_recovery_mode(self) -> _builtins.str:
        return pulumi.get(self, "wal_recovery_mode")

    @_builtins.property
    @pulumi.getter(name="accountIndex")
    def account_index(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "account_index")

    @_builtins.property
    @pulumi.getter(name="accountIndexExcludeKey")
    def account_index_exclude_key(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "account_index_exclude_key")

    @_builtins.property
    @pulumi.getter(name="accountIndexIncludeKey")
    def account_index_include_key(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "account_index_include_key")

    @_builtins.property
    @pulumi.getter(name="accountShrinkPath")
    def account_shrink_path(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "account_shrink_path")

    @_builtins.property
    @pulumi.getter(name="accountsDbCacheLimitMb")
    def accounts_db_cache_limit_mb(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "accounts_db_cache_limit_mb")

    @_builtins.property
    @pulumi.getter(name="accountsDbTestHashCalculation")
    def accounts_db_test_hash_calculation(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "accounts_db_test_hash_calculation")

    @_builtins.property
    @pulumi.getter(name="accountsHashCachePath")
    def accounts_hash_cache_path(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "accounts_hash_cache_path")

    @_builtins.property
    @pulumi.getter(name="accountsIndexBins")
    def accounts_index_bins(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "accounts_index_bins")

    @_builtins.property
    @pulumi.getter(name="accountsIndexPath")
    def accounts_index_path(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "accounts_index_path")

    @_builtins.property
    @pulumi.getter(name="accountsIndexScanResultsLimitMb")
    def accounts_index_scan_results_limit_mb(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "accounts_index_scan_results_limit_mb")

    @_builtins.property
    @pulumi.getter(name="accountsShrinkOptimizeTotalSpace")
    def accounts_shrink_optimize_total_space(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "accounts_shrink_optimize_total_space")

    @_builtins.property
    @pulumi.getter(name="accountsShrinkRatio")
    def accounts_shrink_ratio(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "accounts_shrink_ratio")

    @_builtins.property
    @pulumi.getter(name="allowPrivateAddr")
    def allow_private_addr(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "allow_private_addr")

    @_builtins.property
    @pulumi.getter(name="authorizedVoter")
    def authorized_voter(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "authorized_voter")

    @_builtins.property
    @pulumi.getter(name="bindAddress")
    def bind_address(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "bind_address")

    @_builtins.property
    @pulumi.getter(name="blockProductionMethod")
    def block_production_method(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "block_production_method")

    @_builtins.property
    @pulumi.getter(name="blockVerificationMethod")
    def block_verification_method(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "block_verification_method")

    @_builtins.property
    @pulumi.getter(name="checkVoteAccount")
    def check_vote_account(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "check_vote_account")

    @_builtins.property
    @pulumi.getter(name="contactDebugInterval")
    def contact_debug_interval(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "contact_debug_interval")

    @_builtins.property
    @pulumi.getter
    def cuda(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "cuda")

    @_builtins.property
    @pulumi.getter(name="debugKey")
    def debug_key(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "debug_key")

    @_builtins.property
    @pulumi.getter(name="devHaltAtSlot")
    def dev_halt_at_slot(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "dev_halt_at_slot")

    @_builtins.property
    @pulumi.getter(name="disableBankingTrace")
    def disable_banking_trace(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "disable_banking_trace")

    @_builtins.property
    @pulumi.getter(name="dynamicPortRange")
    def dynamic_port_range(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "dynamic_port_range")

    @_builtins.property
    @pulumi.getter(name="enableBankingTrace")
    def enable_banking_trace(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "enable_banking_trace")

    @_builtins.property
    @pulumi.getter(name="enableBigtableLedgerUpload")
    def enable_bigtable_ledger_upload(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "enable_bigtable_ledger_upload")

    @_builtins.property
    @pulumi.getter(name="enableExtendedTxMetadataStorage")
    def enable_extended_tx_metadata_storage(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "enable_extended_tx_metadata_storage")

    @_builtins.property
    @pulumi.getter(name="enableRpcBigtableLedgerStorage")
    def enable_rpc_bigtable_ledger_storage(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "enable_rpc_bigtable_ledger_storage")

    @_builtins.property
    @pulumi.getter(name="enableRpcTransactionHistory")
    def enable_rpc_transaction_history(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "enable_rpc_transaction_history")

    @_builtins.property
    @pulumi.getter(name="entryPoint")
    def entry_point(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "entry_point")

    @_builtins.property
    @pulumi.getter(name="etcdCacertFile")
    def etcd_cacert_file(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "etcd_cacert_file")

    @_builtins.property
    @pulumi.getter(name="etcdCertFile")
    def etcd_cert_file(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "etcd_cert_file")

    @_builtins.property
    @pulumi.getter(name="etcdDomainName")
    def etcd_domain_name(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "etcd_domain_name")

    @_builtins.property
    @pulumi.getter(name="etcdEndpoint")
    def etcd_endpoint(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "etcd_endpoint")

    @_builtins.property
    @pulumi.getter(name="etcdKeyFile")
    def etcd_key_file(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "etcd_key_file")

    @_builtins.property
    @pulumi.getter(name="expectedBankHash")
    def expected_bank_hash(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "expected_bank_hash")

    @_builtins.property
    @pulumi.getter(name="expectedGenesisHash")
    def expected_genesis_hash(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "expected_genesis_hash")

    @_builtins.property
    @pulumi.getter(name="expectedShredVersion")
    def expected_shred_version(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "expected_shred_version")

    @_builtins.property
    @pulumi.getter(name="extraFlags")
    def extra_flags(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "extra_flags")

    @_builtins.property
    @pulumi.getter(name="fullRpcAPI")
    def full_rpc_api(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "full_rpc_api")

    @_builtins.property
    @pulumi.getter(name="fullSnapshotArchivePath")
    def full_snapshot_archive_path(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "full_snapshot_archive_path")

    @_builtins.property
    @pulumi.getter(name="fullSnapshotIntervalSlots")
    def full_snapshot_interval_slots(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "full_snapshot_interval_slots")

    @_builtins.property
    @pulumi.getter(name="geyserPluginAlwaysEnabled")
    def geyser_plugin_always_enabled(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "geyser_plugin_always_enabled")

    @_builtins.property
    @pulumi.getter(name="geyserPluginConfig")
    def geyser_plugin_config(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "geyser_plugin_config")

    @_builtins.property
    @pulumi.getter(name="gossipHost")
    def gossip_host(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "gossip_host")

    @_builtins.property
    @pulumi.getter(name="gossipPort")
    def gossip_port(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "gossip_port")

    @_builtins.property
    @pulumi.getter(name="gossipValidator")
    def gossip_validator(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "gossip_validator")

    @_builtins.property
    @pulumi.getter(name="hardFork")
    def hard_fork(self) -> Optional[Sequence[_builtins.int]]:
        return pulumi.get(self, "hard_fork")

    @_builtins.property
    @pulumi.getter(name="healthCheckSlotDistance")
    def health_check_slot_distance(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "health_check_slot_distance")

    @_builtins.property
    @pulumi.getter(name="incrementalSnapshotArchivePath")
    def incremental_snapshot_archive_path(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "incremental_snapshot_archive_path")

    @_builtins.property
    @pulumi.getter(name="initCompleteFile")
    def init_complete_file(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "init_complete_file")

    @_builtins.property
    @pulumi.getter(name="knownValidator")
    def known_validator(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "known_validator")

    @_builtins.property
    @pulumi.getter(name="limitLedgerSize")
    def limit_ledger_size(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "limit_ledger_size")

    @_builtins.property
    @pulumi.getter
    def log(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "log")

    @_builtins.property
    @pulumi.getter(name="logMessagesBytesLimit")
    def log_messages_bytes_limit(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "log_messages_bytes_limit")

    @_builtins.property
    @pulumi.getter(name="maxGenesisArchiveUnpackedSize")
    def max_genesis_archive_unpacked_size(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "max_genesis_archive_unpacked_size")

    @_builtins.property
    @pulumi.getter(name="maximumFullSnapshotsToRetain")
    def maximum_full_snapshots_to_retain(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "maximum_full_snapshots_to_retain")

    @_builtins.property
    @pulumi.getter(name="maximumIncrementalSnapshotsToRetain")
    def maximum_incremental_snapshots_to_retain(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "maximum_incremental_snapshots_to_retain")

    @_builtins.property
    @pulumi.getter(name="maximumLocalSnapshotAge")
    def maximum_local_snapshot_age(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "maximum_local_snapshot_age")

    @_builtins.property
    @pulumi.getter(name="maximumSnapshotDownloadAbort")
    def maximum_snapshot_download_abort(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "maximum_snapshot_download_abort")

    @_builtins.property
    @pulumi.getter(name="minimalSnapshotDownloadSpeed")
    def minimal_snapshot_download_speed(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "minimal_snapshot_download_speed")

    @_builtins.property
    @pulumi.getter(name="noGenesisFetch")
    def no_genesis_fetch(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "no_genesis_fetch")

    @_builtins.property
    @pulumi.getter(name="noIncrementalSnapshots")
    def no_incremental_snapshots(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "no_incremental_snapshots")

    @_builtins.property
    @pulumi.getter(name="noSnapshotFetch")
    def no_snapshot_fetch(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "no_snapshot_fetch")

    @_builtins.property
    @pulumi.getter(name="noVoting")
    def no_voting(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "no_voting")

    @_builtins.property
    @pulumi.getter(name="onlyKnownRPC")
    def only_known_rpc(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "only_known_rpc")

    @_builtins.property
    @pulumi.getter(name="privateRPC")
    def private_rpc(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "private_rpc")

    @_builtins.property
    @pulumi.getter(name="publicRpcAddress")
    def public_rpc_address(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "public_rpc_address")

    @_builtins.property
    @pulumi.getter(name="publicTpuAddress")
    def public_tpu_address(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "public_tpu_address")

    @_builtins.property
    @pulumi.getter(name="publicTpuForwardsAddress")
    def public_tpu_forwards_address(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "public_tpu_forwards_address")

    @_builtins.property
    @pulumi.getter(name="repairValidator")
    def repair_validator(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "repair_validator")

    @_builtins.property
    @pulumi.getter(name="requireTower")
    def require_tower(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "require_tower")

    @_builtins.property
    @pulumi.getter(name="restrictedRepairOnlyMode")
    def restricted_repair_only_mode(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "restricted_repair_only_mode")

    @_builtins.property
    @pulumi.getter(name="rocksdbFifoShredStorageSize")
    def rocksdb_fifo_shred_storage_size(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "rocksdb_fifo_shred_storage_size")

    @_builtins.property
    @pulumi.getter(name="rocksdbShredCompaction")
    def rocksdb_shred_compaction(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "rocksdb_shred_compaction")

    @_builtins.property
    @pulumi.getter(name="rpcBigtableAppProfileId")
    def rpc_bigtable_app_profile_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "rpc_bigtable_app_profile_id")

    @_builtins.property
    @pulumi.getter(name="rpcBigtableInstanceName")
    def rpc_bigtable_instance_name(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "rpc_bigtable_instance_name")

    @_builtins.property
    @pulumi.getter(name="rpcBigtableMaxMessageSize")
    def rpc_bigtable_max_message_size(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "rpc_bigtable_max_message_size")

    @_builtins.property
    @pulumi.getter(name="rpcBigtableTimeout")
    def rpc_bigtable_timeout(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "rpc_bigtable_timeout")

    @_builtins.property
    @pulumi.getter(name="rpcFaucetAddress")
    def rpc_faucet_address(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "rpc_faucet_address")

    @_builtins.property
    @pulumi.getter(name="rpcMaxMultipleAccounts")
    def rpc_max_multiple_accounts(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "rpc_max_multiple_accounts")

    @_builtins.property
    @pulumi.getter(name="rpcMaxRequestBodySize")
    def rpc_max_request_body_size(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "rpc_max_request_body_size")

    @_builtins.property
    @pulumi.getter(name="rpcNicenessAdjustment")
    def rpc_niceness_adjustment(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "rpc_niceness_adjustment")

    @_builtins.property
    @pulumi.getter(name="rpcPubsubEnableBlockSubscription")
    def rpc_pubsub_enable_block_subscription(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "rpc_pubsub_enable_block_subscription")

    @_builtins.property
    @pulumi.getter(name="rpcPubsubEnableVoteSubscription")
    def rpc_pubsub_enable_vote_subscription(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "rpc_pubsub_enable_vote_subscription")

    @_builtins.property
    @pulumi.getter(name="rpcPubsubMaxActiveSubscriptions")
    def rpc_pubsub_max_active_subscriptions(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "rpc_pubsub_max_active_subscriptions")

    @_builtins.property
    @pulumi.getter(name="rpcPubsubNotificationThreads")
    def rpc_pubsub_notification_threads(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "rpc_pubsub_notification_threads")

    @_builtins.property
    @pulumi.getter(name="rpcPubsubQueueCapacityBytes")
    def rpc_pubsub_queue_capacity_bytes(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "rpc_pubsub_queue_capacity_bytes")

    @_builtins.property
    @pulumi.getter(name="rpcPubsubQueueCapacityItems")
    def rpc_pubsub_queue_capacity_items(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "rpc_pubsub_queue_capacity_items")

    @_builtins.property
    @pulumi.getter(name="rpcPubsubWorkerThreads")
    def rpc_pubsub_worker_threads(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "rpc_pubsub_worker_threads")

    @_builtins.property
    @pulumi.getter(name="rpcScanAndFixRoots")
    def rpc_scan_and_fix_roots(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "rpc_scan_and_fix_roots")

    @_builtins.property
    @pulumi.getter(name="rpcSendLeaderCount")
    def rpc_send_leader_count(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "rpc_send_leader_count")

    @_builtins.property
    @pulumi.getter(name="rpcSendRetryMs")
    def rpc_send_retry_ms(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "rpc_send_retry_ms")

    @_builtins.property
    @pulumi.getter(name="rpcSendServiceMaxRetries")
    def rpc_send_service_max_retries(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "rpc_send_service_max_retries")

    @_builtins.property
    @pulumi.getter(name="rpcSendTransactionAlsoLeader")
    def rpc_send_transaction_also_leader(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "rpc_send_transaction_also_leader")

    @_builtins.property
    @pulumi.getter(name="rpcSendTransactionRetryPoolMaxSize")
    def rpc_send_transaction_retry_pool_max_size(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "rpc_send_transaction_retry_pool_max_size")

    @_builtins.property
    @pulumi.getter(name="rpcSendTransactionTpuPeer")
    def rpc_send_transaction_tpu_peer(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "rpc_send_transaction_tpu_peer")

    @_builtins.property
    @pulumi.getter(name="rpcThreads")
    def rpc_threads(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "rpc_threads")

    @_builtins.property
    @pulumi.getter(name="skipPreflightHealthCheck")
    def skip_preflight_health_check(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "skip_preflight_health_check")

    @_builtins.property
    @pulumi.getter(name="skipSeedPhraseValidation")
    def skip_seed_phrase_validation(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "skip_seed_phrase_validation")

    @_builtins.property
    @pulumi.getter(name="skipStartupLedgerVerification")
    def skip_startup_ledger_verification(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "skip_startup_ledger_verification")

    @_builtins.property
    @pulumi.getter(name="snapshotArchiveFormat")
    def snapshot_archive_format(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "snapshot_archive_format")

    @_builtins.property
    @pulumi.getter(name="snapshotIntervalSlots")
    def snapshot_interval_slots(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "snapshot_interval_slots")

    @_builtins.property
    @pulumi.getter(name="snapshotPackagerNicenessAdjustment")
    def snapshot_packager_niceness_adjustment(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "snapshot_packager_niceness_adjustment")

    @_builtins.property
    @pulumi.getter(name="snapshotVersion")
    def snapshot_version(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "snapshot_version")

    @_builtins.property
    @pulumi.getter(name="stakedNodesOverrides")
    def staked_nodes_overrides(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "staked_nodes_overrides")

    @_builtins.property
    @pulumi.getter(name="towerStorage")
    def tower_storage(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "tower_storage")

    @_builtins.property
    @pulumi.getter(name="tpuCoalesceMs")
    def tpu_coalesce_ms(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "tpu_coalesce_ms")

    @_builtins.property
    @pulumi.getter(name="tpuConnectionPoolSize")
    def tpu_connection_pool_size(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "tpu_connection_pool_size")

    @_builtins.property
    @pulumi.getter(name="tpuDisableQuic")
    def tpu_disable_quic(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "tpu_disable_quic")

    @_builtins.property
    @pulumi.getter(name="tpuEnableUdp")
    def tpu_enable_udp(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "tpu_enable_udp")

    @_builtins.property
    @pulumi.getter(name="tvuReceiveThreads")
    def tvu_receive_threads(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "tvu_receive_threads")

    @_builtins.property
    @pulumi.getter(name="unifiedSchedulerHandlerThreads")
    def unified_scheduler_handler_threads(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "unified_scheduler_handler_threads")

    @_builtins.property
    @pulumi.getter(name="useSnapshotArchivesAtStartup")
    def use_snapshot_archives_at_startup(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "use_snapshot_archives_at_startup")

    @_builtins.property
    @pulumi.getter(name="waitForSupermajority")
    def wait_for_supermajority(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "wait_for_supermajority")


@pulumi.output_type
class KeyPairs(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "voteAccount":
            suggest = "vote_account"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in KeyPairs. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        KeyPairs.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        KeyPairs.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 identity: _builtins.str,
                 vote_account: _builtins.str):
        pulumi.set(__self__, "identity", identity)
        pulumi.set(__self__, "vote_account", vote_account)

    @_builtins.property
    @pulumi.getter
    def identity(self) -> _builtins.str:
        return pulumi.get(self, "identity")

    @_builtins.property
    @pulumi.getter(name="voteAccount")
    def vote_account(self) -> _builtins.str:
        return pulumi.get(self, "vote_account")


@pulumi.output_type
class Metrics(dict):
    def __init__(__self__, *,
                 database: _builtins.str,
                 password: _builtins.str,
                 url: _builtins.str,
                 user: _builtins.str):
        pulumi.set(__self__, "database", database)
        pulumi.set(__self__, "password", password)
        pulumi.set(__self__, "url", url)
        pulumi.set(__self__, "user", user)

    @_builtins.property
    @pulumi.getter
    def database(self) -> _builtins.str:
        return pulumi.get(self, "database")

    @_builtins.property
    @pulumi.getter
    def password(self) -> _builtins.str:
        return pulumi.get(self, "password")

    @_builtins.property
    @pulumi.getter
    def url(self) -> _builtins.str:
        return pulumi.get(self, "url")

    @_builtins.property
    @pulumi.getter
    def user(self) -> _builtins.str:
        return pulumi.get(self, "user")


@pulumi.output_type
class ShutdownPolicy(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "maxDelinquentStake":
            suggest = "max_delinquent_stake"
        elif key == "minIdleTime":
            suggest = "min_idle_time"
        elif key == "skipHealthCheck":
            suggest = "skip_health_check"
        elif key == "skipNewSnapshotCheck":
            suggest = "skip_new_snapshot_check"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ShutdownPolicy. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ShutdownPolicy.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ShutdownPolicy.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 force: Optional[_builtins.bool] = None,
                 max_delinquent_stake: Optional[_builtins.int] = None,
                 min_idle_time: Optional[_builtins.int] = None,
                 skip_health_check: Optional[_builtins.bool] = None,
                 skip_new_snapshot_check: Optional[_builtins.bool] = None):
        if force is not None:
            pulumi.set(__self__, "force", force)
        if max_delinquent_stake is not None:
            pulumi.set(__self__, "max_delinquent_stake", max_delinquent_stake)
        if min_idle_time is not None:
            pulumi.set(__self__, "min_idle_time", min_idle_time)
        if skip_health_check is not None:
            pulumi.set(__self__, "skip_health_check", skip_health_check)
        if skip_new_snapshot_check is not None:
            pulumi.set(__self__, "skip_new_snapshot_check", skip_new_snapshot_check)

    @_builtins.property
    @pulumi.getter
    def force(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "force")

    @_builtins.property
    @pulumi.getter(name="maxDelinquentStake")
    def max_delinquent_stake(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "max_delinquent_stake")

    @_builtins.property
    @pulumi.getter(name="minIdleTime")
    def min_idle_time(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "min_idle_time")

    @_builtins.property
    @pulumi.getter(name="skipHealthCheck")
    def skip_health_check(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "skip_health_check")

    @_builtins.property
    @pulumi.getter(name="skipNewSnapshotCheck")
    def skip_new_snapshot_check(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "skip_new_snapshot_check")


@pulumi.output_type
class StartupPolicy(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "waitForRPCHealth":
            suggest = "wait_for_rpc_health"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in StartupPolicy. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        StartupPolicy.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        StartupPolicy.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 wait_for_rpc_health: Optional[_builtins.bool] = None):
        if wait_for_rpc_health is not None:
            pulumi.set(__self__, "wait_for_rpc_health", wait_for_rpc_health)

    @_builtins.property
    @pulumi.getter(name="waitForRPCHealth")
    def wait_for_rpc_health(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "wait_for_rpc_health")


@pulumi.output_type
class TimeoutConfig(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "rpcServiceTimeout":
            suggest = "rpc_service_timeout"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in TimeoutConfig. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        TimeoutConfig.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        TimeoutConfig.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 rpc_service_timeout: Optional[_builtins.int] = None):
        if rpc_service_timeout is not None:
            pulumi.set(__self__, "rpc_service_timeout", rpc_service_timeout)

    @_builtins.property
    @pulumi.getter(name="rpcServiceTimeout")
    def rpc_service_timeout(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "rpc_service_timeout")


