version: 2
archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
builds:
  - binary: pulumi-resource-svmkit
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/abklabs/pulumi-svmkit/pkg/version.Version={{.Tag }}
    main: ./cmd/pulumi-resource-svmkit/
changelog:
  disable: true
release:
  disable: false
  prerelease: auto
snapshot:
  version_template: '{{ .Tag }}-SNAPSHOT'
