name: svmkit
types:
    # svmkit:index:GenesisConfig:
    #     type: object
    #     properties:
    #         ledgerPath:
    #             type: string
    #         identityPubkey:
    #             type: string
    #         votePubkey:
    #             type: string
    #         stakePubkey:
    #             type: string
    #         faucetPubkey:
    #             type: string
    #         faucetLamports:
    #             type: string
    #         targetLamportsPerSignature:
    #             type: string
    #         inflation:
    #             type: string
    #         lamportsPerByteYear:
    #             type: string
    #         slotPerEpoch:
    #             type: string
    #         clusterType:
    #             type: string
    # svmkit:index:BackendValidatorConfig:
    #     type: object
    #     properties:
    #         identityKeyPair:
    #             type: string
    #         voteAccountKeyPair:
    #             type: string
    #         stakeAccountKeyPair:
    #             type: string
    #         entryPoint:
    #             type: array
    #             items:
    #                 type: string
    #         knownValidator:
    #             type: array
    #             items:
    #                 type: string
    #         useSnapshotArchivesAtStartup:
    #             type: string
    #         rpcPort:
    #             type: number
    #         gossipPort:
    #             type: number
    #         privateRPC:
    #             type: boolean
    #         onlyKnownRPC:
    #             type: boolean
    #         noWaitForVoteToStartLeader:
    #             type: boolean
    #         fullSnapshotIntervalSlots:
    #             type: number
    #         dynamicPortRange:
    #             type: string
    #         rpcBindAddress:
    #             type: string
    #         walRecoveryMode:
    #             type: string
    #         limitLedgerSize:
    #             type: number
    #         blockProductionMethod:
    #             type: string
    #         paths:
    #             type: object
    #             properties:
    #                 accounts:
    #                     type: string
    #                 ledger:
    #                     type: string
    #                 log:
    #                     type: string
resources:
    # svmkit:index:Genesis:
    #     isComponent: true
    #     inputProperties:
    #         connection:
    #             $ref: /command/v1.0.1/schema.json#/types/command:remote:Connection
    #         genesisConfig:
    #             $ref: "#/types/svmkit:index:GenesisConfig"
    #         triggers:
    #             type: array
    #             items:
    #                 $ref: pulumi.json#/Any
    #             plain: true
    #     requiredInputs:
    #         - connection
    #         - genesisConfig
    svmkit:index:Validator:
        isComponent: true
        inputProperties:
            connection:
                $ref: /command/v1.0.1/schema.json#/types/command:remote:Connection
            identity:
                type: string
            stakeAccount:
                type: string
            voteAccount:
                type: string
            user:
                type: string
        requiredInputs:
            - connection
            - identity
            - voteAccount
            - user
        properties: {}
        required: []
    svmkit:index:KeyPair:
        isComponent: true
        inputProperties: {}
        properties:
            publicKey:
                type: string
            privateKey:
                type: array
                items:
                    type: integer
            json:
                type: string
        required:
            - publicKey
            - privateKey
            - json
    svmkit:index:Ready:
        isComponent: true
        inputProperties:
            connection:
                $ref: /command/v1.0.1/schema.json#/types/command:remote:Connection
            customTimeout:
                type: string
        requiredInputs:
            - connection
        properties: {}
        required: []
    svmkit:index:User:
        isComponent: true
        properties:
            name:
                type: string
        inputProperties:
            connection:
                $ref: /command/v1.0.1/schema.json#/types/command:remote:Connection
            username:
                type: string
        requiredInputs:
            - connection
            - username
        required:
            - name
language:
    csharp:
        packageReferences:
            Pulumi: "3.*"
            Pulumi.Command: "1.*"
    go:
        generateResourceContainerTypes: true
        importBasePath: github.com/abklabs/pulumi-svmkit/sdk/go/svmkit
    nodejs:
        dependencies:
            "@pulumi/command": "^1.0.0"
        devDependencies:
            typescript: "^4.6.3"
    python:
        requires:
            pulumi: ">=3.0.0,<4.0.0"
            pulumi-command: ">=1.0.0"
