// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Genesis.Inputs
{

    public sealed class BootstrapValidatorArgs : global::Pulumi.ResourceArgs
    {
        [Input("identityPubkey", required: true)]
        public Input<string> IdentityPubkey { get; set; } = null!;

        [Input("stakePubkey", required: true)]
        public Input<string> StakePubkey { get; set; } = null!;

        [Input("votePubkey", required: true)]
        public Input<string> VotePubkey { get; set; } = null!;

        public BootstrapValidatorArgs()
        {
        }
        public static new BootstrapValidatorArgs Empty => new BootstrapValidatorArgs();
    }
}
