// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Account
{
    [SvmkitResourceType("svmkit:account:StakeAccount")]
    public partial class StakeAccount : global::Pulumi.CustomResource
    {
        [Output("amount")]
        public Output<double> Amount { get; private set; } = null!;

        [Output("connection")]
        public Output<ABKLabs.Svmkit.Ssh.Outputs.Connection> Connection { get; private set; } = null!;

        [Output("keyPairs")]
        public Output<ABKLabs.Svmkit.Solana.Outputs.StakeAccountKeyPairs> KeyPairs { get; private set; } = null!;

        [Output("transactionOptions")]
        public Output<ABKLabs.Svmkit.Solana.Outputs.TxnOptions> TransactionOptions { get; private set; } = null!;


        /// <summary>
        /// Create a StakeAccount resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public StakeAccount(string name, StakeAccountArgs args, CustomResourceOptions? options = null)
            : base("svmkit:account:StakeAccount", name, args ?? new StakeAccountArgs(), MakeResourceOptions(options, ""))
        {
        }

        private StakeAccount(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("svmkit:account:StakeAccount", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/abklabs",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing StakeAccount resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static StakeAccount Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new StakeAccount(name, id, options);
        }
    }

    public sealed class StakeAccountArgs : global::Pulumi.ResourceArgs
    {
        [Input("amount", required: true)]
        public Input<double> Amount { get; set; } = null!;

        [Input("connection", required: true)]
        public Input<ABKLabs.Svmkit.Ssh.Inputs.ConnectionArgs> Connection { get; set; } = null!;

        [Input("keyPairs", required: true)]
        public Input<ABKLabs.Svmkit.Solana.Inputs.StakeAccountKeyPairsArgs> KeyPairs { get; set; } = null!;

        [Input("transactionOptions", required: true)]
        public Input<ABKLabs.Svmkit.Solana.Inputs.TxnOptionsArgs> TransactionOptions { get; set; } = null!;

        public StakeAccountArgs()
        {
        }
        public static new StakeAccountArgs Empty => new StakeAccountArgs();
    }
}
