# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'Package',
    'PackageConfig',
]

@pulumi.output_type
class Package(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "targetRelease":
            suggest = "target_release"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in Package. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        Package.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        Package.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 name: str,
                 path: Optional[str] = None,
                 target_release: Optional[str] = None,
                 version: Optional[str] = None):
        pulumi.set(__self__, "name", name)
        if path is not None:
            pulumi.set(__self__, "path", path)
        if target_release is not None:
            pulumi.set(__self__, "target_release", target_release)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @property
    @pulumi.getter
    def name(self) -> str:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def path(self) -> Optional[str]:
        return pulumi.get(self, "path")

    @property
    @pulumi.getter(name="targetRelease")
    def target_release(self) -> Optional[str]:
        return pulumi.get(self, "target_release")

    @property
    @pulumi.getter
    def version(self) -> Optional[str]:
        return pulumi.get(self, "version")


@pulumi.output_type
class PackageConfig(dict):
    def __init__(__self__, *,
                 additional: Optional[Sequence[str]] = None,
                 override: Optional[Sequence['outputs.Package']] = None):
        if additional is not None:
            pulumi.set(__self__, "additional", additional)
        if override is not None:
            pulumi.set(__self__, "override", override)

    @property
    @pulumi.getter
    def additional(self) -> Optional[Sequence[str]]:
        return pulumi.get(self, "additional")

    @property
    @pulumi.getter
    def override(self) -> Optional[Sequence['outputs.Package']]:
        return pulumi.get(self, "override")


