// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Firedancer.Outputs
{

    [OutputType]
    public sealed class ConfigReporting
    {
        public readonly string? SolanaMetricsConfig;

        [OutputConstructor]
        private ConfigReporting(string? solanaMetricsConfig)
        {
            SolanaMetricsConfig = solanaMetricsConfig;
        }
    }
}
