// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Firedancer.Outputs
{

    [OutputType]
    public sealed class ConfigLayout
    {
        public readonly string? Affinity;
        public readonly string? AgaveAffinity;
        public readonly int? BankTileCount;
        public readonly int? NetTileCount;
        public readonly int? QuicTileCount;
        public readonly int? ResolvTileCount;
        public readonly int? ShredTileCount;
        public readonly int? VerifyTileCount;

        [OutputConstructor]
        private ConfigLayout(
            string? affinity,

            string? agaveAffinity,

            int? bankTileCount,

            int? netTileCount,

            int? quicTileCount,

            int? resolvTileCount,

            int? shredTileCount,

            int? verifyTileCount)
        {
            Affinity = affinity;
            AgaveAffinity = agaveAffinity;
            BankTileCount = bankTileCount;
            NetTileCount = netTileCount;
            QuicTileCount = quicTileCount;
            ResolvTileCount = resolvTileCount;
            ShredTileCount = shredTileCount;
            VerifyTileCount = verifyTileCount;
        }
    }
}
