// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Firedancer.Outputs
{

    [OutputType]
    public sealed class ConfigHugeTLBFS
    {
        public readonly string? MountPath;

        [OutputConstructor]
        private ConfigHugeTLBFS(string? mountPath)
        {
            MountPath = mountPath;
        }
    }
}
