// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Watchtower.Inputs
{

    public sealed class PagerDutyConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("integrationKey", required: true)]
        public Input<string> IntegrationKey { get; set; } = null!;

        public PagerDutyConfigArgs()
        {
        }
        public static new PagerDutyConfigArgs Empty => new PagerDutyConfigArgs();
    }
}
