// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Watchtower.Inputs
{

    public sealed class TelegramConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("botToken", required: true)]
        public Input<string> BotToken { get; set; } = null!;

        [Input("chatId", required: true)]
        public Input<string> ChatId { get; set; } = null!;

        public TelegramConfigArgs()
        {
        }
        public static new TelegramConfigArgs Empty => new TelegramConfigArgs();
    }
}
