// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Geyser.Outputs
{

    [OutputType]
    public sealed class GrpcConfigFilterLimitsAccounts
    {
        public readonly int? AccountMax;
        public readonly ImmutableArray<string> AccountReject;
        public readonly bool? Any;
        public readonly int? DataSliceMax;
        public readonly int? Max;
        public readonly int? OwnerMax;
        public readonly ImmutableArray<string> OwnerReject;

        [OutputConstructor]
        private GrpcConfigFilterLimitsAccounts(
            int? accountMax,

            ImmutableArray<string> accountReject,

            bool? any,

            int? dataSliceMax,

            int? max,

            int? ownerMax,

            ImmutableArray<string> ownerReject)
        {
            AccountMax = accountMax;
            AccountReject = accountReject;
            Any = any;
            DataSliceMax = dataSliceMax;
            Max = max;
            OwnerMax = ownerMax;
            OwnerReject = ownerReject;
        }
    }
}
