// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Geyser.Outputs
{

    [OutputType]
    public sealed class GrpcConfigFilterLimits
    {
        public readonly Outputs.GrpcConfigFilterLimitsAccounts? Accounts;
        public readonly Outputs.GrpcConfigFilterLimitsBlocks? Blocks;
        public readonly Outputs.GrpcConfigFilterLimitsBlocksMeta? BlocksMeta;
        public readonly Outputs.GrpcConfigFilterLimitsEntries? Entries;
        public readonly Outputs.GrpcConfigFilterLimitsSlots? Slots;
        public readonly Outputs.GrpcConfigFilterLimitsTransactions? Transactions;
        public readonly Outputs.GrpcConfigFilterLimitsTransactions? TransactionsStatus;

        [OutputConstructor]
        private GrpcConfigFilterLimits(
            Outputs.GrpcConfigFilterLimitsAccounts? accounts,

            Outputs.GrpcConfigFilterLimitsBlocks? blocks,

            Outputs.GrpcConfigFilterLimitsBlocksMeta? blocksMeta,

            Outputs.GrpcConfigFilterLimitsEntries? entries,

            Outputs.GrpcConfigFilterLimitsSlots? slots,

            Outputs.GrpcConfigFilterLimitsTransactions? transactions,

            Outputs.GrpcConfigFilterLimitsTransactions? transactionsStatus)
        {
            Accounts = accounts;
            Blocks = blocks;
            BlocksMeta = blocksMeta;
            Entries = entries;
            Slots = slots;
            Transactions = transactions;
            TransactionsStatus = transactionsStatus;
        }
    }
}
