// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Solana.Outputs
{

    [OutputType]
    public sealed class VoteAccountKeyPairs
    {
        public readonly string AuthWithdrawer;
        public readonly string Identity;
        public readonly string VoteAccount;

        [OutputConstructor]
        private VoteAccountKeyPairs(
            string authWithdrawer,

            string identity,

            string voteAccount)
        {
            AuthWithdrawer = authWithdrawer;
            Identity = identity;
            VoteAccount = voteAccount;
        }
    }
}
