// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Tuner.Inputs
{

    public sealed class TunerKernelParamsArgs : global::Pulumi.ResourceArgs
    {
        [Input("kernelHungTaskTimeoutSecs")]
        public Input<int>? KernelHungTaskTimeoutSecs { get; set; }

        [Input("kernelNmiWatchdog")]
        public Input<int>? KernelNmiWatchdog { get; set; }

        [Input("kernelPidMax")]
        public Input<int>? KernelPidMax { get; set; }

        [Input("kernelSchedMinGranularityNs")]
        public Input<int>? KernelSchedMinGranularityNs { get; set; }

        [Input("kernelSchedWakeupGranularityNs")]
        public Input<int>? KernelSchedWakeupGranularityNs { get; set; }

        [Input("kernelTimerMigration")]
        public Input<int>? KernelTimerMigration { get; set; }

        public TunerKernelParamsArgs()
        {
        }
        public static new TunerKernelParamsArgs Empty => new TunerKernelParamsArgs();
    }
}
