// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Agave.Inputs
{

    public sealed class TimeoutConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("rpcServiceTimeout")]
        public Input<int>? RpcServiceTimeout { get; set; }

        public TimeoutConfigArgs()
        {
        }
        public static new TimeoutConfigArgs Empty => new TimeoutConfigArgs();
    }
}
