// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Apt.Outputs
{

    [OutputType]
    public sealed class Source
    {
        public readonly ImmutableArray<string> URIs;
        public readonly bool? AllowDowngradeToInsecure;
        public readonly bool? AllowInsecure;
        public readonly bool? AllowWeak;
        public readonly ImmutableArray<string> Architectures;
        public readonly bool? CheckDate;
        public readonly bool? CheckValidUntil;
        public readonly ImmutableArray<string> Components;
        public readonly int? DateMaxFuture;
        public readonly ImmutableArray<string> ExtraLines;
        public readonly string? InReleasePath;
        public readonly Outputs.SignedBy? SignedBy;
        public readonly string? Snapshot;
        public readonly ImmutableArray<string> Suites;
        public readonly bool? Trusted;
        public readonly ImmutableArray<string> Types;
        public readonly int? ValidUntilMax;
        public readonly int? ValidUntilMin;

        [OutputConstructor]
        private Source(
            ImmutableArray<string> URIs,

            bool? allowDowngradeToInsecure,

            bool? allowInsecure,

            bool? allowWeak,

            ImmutableArray<string> architectures,

            bool? checkDate,

            bool? checkValidUntil,

            ImmutableArray<string> components,

            int? dateMaxFuture,

            ImmutableArray<string> extraLines,

            string? inReleasePath,

            Outputs.SignedBy? signedBy,

            string? snapshot,

            ImmutableArray<string> suites,

            bool? trusted,

            ImmutableArray<string> types,

            int? validUntilMax,

            int? validUntilMin)
        {
            this.URIs = URIs;
            AllowDowngradeToInsecure = allowDowngradeToInsecure;
            AllowInsecure = allowInsecure;
            AllowWeak = allowWeak;
            Architectures = architectures;
            CheckDate = checkDate;
            CheckValidUntil = checkValidUntil;
            Components = components;
            DateMaxFuture = dateMaxFuture;
            ExtraLines = extraLines;
            InReleasePath = inReleasePath;
            SignedBy = signedBy;
            Snapshot = snapshot;
            Suites = suites;
            Trusted = trusted;
            Types = types;
            ValidUntilMax = validUntilMax;
            ValidUntilMin = validUntilMin;
        }
    }
}
