// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export class Firedancer extends pulumi.CustomResource {
    /**
     * Get an existing Firedancer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Firedancer {
        return new Firedancer(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'svmkit:validator:Firedancer';

    /**
     * Returns true if the given object is an instance of Firedancer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Firedancer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Firedancer.__pulumiType;
    }

    public readonly config!: pulumi.Output<outputs.firedancer.Config>;
    public readonly connection!: pulumi.Output<outputs.ssh.Connection>;
    public readonly environment!: pulumi.Output<outputs.solana.Environment | undefined>;
    public readonly keyPairs!: pulumi.Output<outputs.firedancer.KeyPairs>;
    public readonly runnerConfig!: pulumi.Output<outputs.runner.Config | undefined>;
    public readonly version!: pulumi.Output<string | undefined>;

    /**
     * Create a Firedancer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FiredancerArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.config === undefined) && !opts.urn) {
                throw new Error("Missing required property 'config'");
            }
            if ((!args || args.connection === undefined) && !opts.urn) {
                throw new Error("Missing required property 'connection'");
            }
            if ((!args || args.keyPairs === undefined) && !opts.urn) {
                throw new Error("Missing required property 'keyPairs'");
            }
            resourceInputs["config"] = args ? args.config : undefined;
            resourceInputs["connection"] = args ? (args.connection ? pulumi.output(args.connection).apply(inputs.ssh.connectionArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["environment"] = args ? args.environment : undefined;
            resourceInputs["keyPairs"] = args ? args.keyPairs : undefined;
            resourceInputs["runnerConfig"] = args ? args.runnerConfig : undefined;
            resourceInputs["version"] = args ? args.version : undefined;
        } else {
            resourceInputs["config"] = undefined /*out*/;
            resourceInputs["connection"] = undefined /*out*/;
            resourceInputs["environment"] = undefined /*out*/;
            resourceInputs["keyPairs"] = undefined /*out*/;
            resourceInputs["runnerConfig"] = undefined /*out*/;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Firedancer.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Firedancer resource.
 */
export interface FiredancerArgs {
    config: pulumi.Input<inputs.firedancer.ConfigArgs>;
    connection: pulumi.Input<inputs.ssh.ConnectionArgs>;
    environment?: pulumi.Input<inputs.solana.EnvironmentArgs>;
    keyPairs: pulumi.Input<inputs.firedancer.KeyPairsArgs>;
    runnerConfig?: pulumi.Input<inputs.runner.ConfigArgs>;
    version?: pulumi.Input<string>;
}
