# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .key_pair import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_svmkit.account as __account
    account = __account
    import pulumi_svmkit.agave as __agave
    agave = __agave
    import pulumi_svmkit.explorer as __explorer
    explorer = __explorer
    import pulumi_svmkit.faucet as __faucet
    faucet = __faucet
    import pulumi_svmkit.firedancer as __firedancer
    firedancer = __firedancer
    import pulumi_svmkit.genesis as __genesis
    genesis = __genesis
    import pulumi_svmkit.networkinfo as __networkinfo
    networkinfo = __networkinfo
    import pulumi_svmkit.solana as __solana
    solana = __solana
    import pulumi_svmkit.ssh as __ssh
    ssh = __ssh
    import pulumi_svmkit.validator as __validator
    validator = __validator
else:
    account = _utilities.lazy_import('pulumi_svmkit.account')
    agave = _utilities.lazy_import('pulumi_svmkit.agave')
    explorer = _utilities.lazy_import('pulumi_svmkit.explorer')
    faucet = _utilities.lazy_import('pulumi_svmkit.faucet')
    firedancer = _utilities.lazy_import('pulumi_svmkit.firedancer')
    genesis = _utilities.lazy_import('pulumi_svmkit.genesis')
    networkinfo = _utilities.lazy_import('pulumi_svmkit.networkinfo')
    solana = _utilities.lazy_import('pulumi_svmkit.solana')
    ssh = _utilities.lazy_import('pulumi_svmkit.ssh')
    validator = _utilities.lazy_import('pulumi_svmkit.validator')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "svmkit",
  "mod": "account",
  "fqn": "pulumi_svmkit.account",
  "classes": {
   "svmkit:account:StakeAccount": "StakeAccount",
   "svmkit:account:Transfer": "Transfer",
   "svmkit:account:VoteAccount": "VoteAccount"
  }
 },
 {
  "pkg": "svmkit",
  "mod": "explorer",
  "fqn": "pulumi_svmkit.explorer",
  "classes": {
   "svmkit:explorer:Explorer": "Explorer"
  }
 },
 {
  "pkg": "svmkit",
  "mod": "faucet",
  "fqn": "pulumi_svmkit.faucet",
  "classes": {
   "svmkit:faucet:Faucet": "Faucet"
  }
 },
 {
  "pkg": "svmkit",
  "mod": "genesis",
  "fqn": "pulumi_svmkit.genesis",
  "classes": {
   "svmkit:genesis:Solana": "Solana"
  }
 },
 {
  "pkg": "svmkit",
  "mod": "index",
  "fqn": "pulumi_svmkit",
  "classes": {
   "svmkit:index:KeyPair": "KeyPair"
  }
 },
 {
  "pkg": "svmkit",
  "mod": "validator",
  "fqn": "pulumi_svmkit.validator",
  "classes": {
   "svmkit:validator:Agave": "Agave",
   "svmkit:validator:Firedancer": "Firedancer"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "svmkit",
  "token": "pulumi:providers:svmkit",
  "fqn": "pulumi_svmkit",
  "class": "Provider"
 }
]
"""
)
