// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Firedancer.Inputs
{

    public sealed class ConfigSnapshotsArgs : global::Pulumi.ResourceArgs
    {
        [Input("fullSnapshotIntervalSlots")]
        public Input<int>? FullSnapshotIntervalSlots { get; set; }

        [Input("incrementalPath")]
        public Input<string>? IncrementalPath { get; set; }

        [Input("incrementalSnapshotIntervalSlots")]
        public Input<int>? IncrementalSnapshotIntervalSlots { get; set; }

        [Input("incrementalSnapshots")]
        public Input<bool>? IncrementalSnapshots { get; set; }

        [Input("maximumFullSnapshotsToRetain")]
        public Input<int>? MaximumFullSnapshotsToRetain { get; set; }

        [Input("maximumIncrementalSnapshotsToRetain")]
        public Input<int>? MaximumIncrementalSnapshotsToRetain { get; set; }

        [Input("minimumSnapshotDownloadSpeed")]
        public Input<int>? MinimumSnapshotDownloadSpeed { get; set; }

        [Input("path")]
        public Input<string>? Path { get; set; }

        public ConfigSnapshotsArgs()
        {
        }
        public static new ConfigSnapshotsArgs Empty => new ConfigSnapshotsArgs();
    }
}
