// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Geyser.Inputs
{

    public sealed class GrpcConfigFilterLimitsEntriesArgs : global::Pulumi.ResourceArgs
    {
        [Input("max")]
        public Input<int>? Max { get; set; }

        public GrpcConfigFilterLimitsEntriesArgs()
        {
        }
        public static new GrpcConfigFilterLimitsEntriesArgs Empty => new GrpcConfigFilterLimitsEntriesArgs();
    }
}
