// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Geyser.Inputs
{

    public sealed class GrpcConfigFilterLimitsAccountsArgs : global::Pulumi.ResourceArgs
    {
        [Input("accountMax")]
        public Input<int>? AccountMax { get; set; }

        [Input("accountReject")]
        private InputList<string>? _accountReject;
        public InputList<string> AccountReject
        {
            get => _accountReject ?? (_accountReject = new InputList<string>());
            set => _accountReject = value;
        }

        [Input("any")]
        public Input<bool>? Any { get; set; }

        [Input("dataSliceMax")]
        public Input<int>? DataSliceMax { get; set; }

        [Input("max")]
        public Input<int>? Max { get; set; }

        [Input("ownerMax")]
        public Input<int>? OwnerMax { get; set; }

        [Input("ownerReject")]
        private InputList<string>? _ownerReject;
        public InputList<string> OwnerReject
        {
            get => _ownerReject ?? (_ownerReject = new InputList<string>());
            set => _ownerReject = value;
        }

        public GrpcConfigFilterLimitsAccountsArgs()
        {
        }
        public static new GrpcConfigFilterLimitsAccountsArgs Empty => new GrpcConfigFilterLimitsAccountsArgs();
    }
}
