// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Geyser.Inputs
{

    public sealed class GrpcConfigGrpcCompressionArgs : global::Pulumi.ResourceArgs
    {
        [Input("accept")]
        private InputList<string>? _accept;
        public InputList<string> Accept
        {
            get => _accept ?? (_accept = new InputList<string>());
            set => _accept = value;
        }

        [Input("send")]
        private InputList<string>? _send;
        public InputList<string> Send
        {
            get => _send ?? (_send = new InputList<string>());
            set => _send = value;
        }

        public GrpcConfigGrpcCompressionArgs()
        {
        }
        public static new GrpcConfigGrpcCompressionArgs Empty => new GrpcConfigGrpcCompressionArgs();
    }
}
