// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Geyser.Inputs
{

    public sealed class GrpcConfigFilterLimitsArgs : global::Pulumi.ResourceArgs
    {
        [Input("accounts")]
        public Input<Inputs.GrpcConfigFilterLimitsAccountsArgs>? Accounts { get; set; }

        [Input("blocks")]
        public Input<Inputs.GrpcConfigFilterLimitsBlocksArgs>? Blocks { get; set; }

        [Input("blocksMeta")]
        public Input<Inputs.GrpcConfigFilterLimitsBlocksMetaArgs>? BlocksMeta { get; set; }

        [Input("entries")]
        public Input<Inputs.GrpcConfigFilterLimitsEntriesArgs>? Entries { get; set; }

        [Input("slots")]
        public Input<Inputs.GrpcConfigFilterLimitsSlotsArgs>? Slots { get; set; }

        [Input("transactions")]
        public Input<Inputs.GrpcConfigFilterLimitsTransactionsArgs>? Transactions { get; set; }

        [Input("transactionsStatus")]
        public Input<Inputs.GrpcConfigFilterLimitsTransactionsArgs>? TransactionsStatus { get; set; }

        public GrpcConfigFilterLimitsArgs()
        {
        }
        public static new GrpcConfigFilterLimitsArgs Empty => new GrpcConfigFilterLimitsArgs();
    }
}
