// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace ABKLabs.Svmkit.Firewall
{
    [EnumType]
    public readonly struct FirewallVariant : IEquatable<FirewallVariant>
    {
        private readonly string _value;

        private FirewallVariant(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        /// <summary>
        /// The generic firewall
        /// </summary>
        public static FirewallVariant Generic { get; } = new FirewallVariant("generic");

        public static bool operator ==(FirewallVariant left, FirewallVariant right) => left.Equals(right);
        public static bool operator !=(FirewallVariant left, FirewallVariant right) => !left.Equals(right);

        public static explicit operator string(FirewallVariant value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is FirewallVariant other && Equals(other);
        public bool Equals(FirewallVariant other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
