// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Firewall
{
    public static class GetDefaultFirewallParams
    {
        public static Task<GetDefaultFirewallParamsResult> InvokeAsync(GetDefaultFirewallParamsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDefaultFirewallParamsResult>("svmkit:firewall:getDefaultFirewallParams", args ?? new GetDefaultFirewallParamsArgs(), options.WithDefaults());

        public static Output<GetDefaultFirewallParamsResult> Invoke(GetDefaultFirewallParamsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDefaultFirewallParamsResult>("svmkit:firewall:getDefaultFirewallParams", args ?? new GetDefaultFirewallParamsInvokeArgs(), options.WithDefaults());

        public static Output<GetDefaultFirewallParamsResult> Invoke(GetDefaultFirewallParamsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDefaultFirewallParamsResult>("svmkit:firewall:getDefaultFirewallParams", args ?? new GetDefaultFirewallParamsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDefaultFirewallParamsArgs : global::Pulumi.InvokeArgs
    {
        [Input("variant", required: true)]
        public ABKLabs.Svmkit.Firewall.FirewallVariant Variant { get; set; }

        public GetDefaultFirewallParamsArgs()
        {
        }
        public static new GetDefaultFirewallParamsArgs Empty => new GetDefaultFirewallParamsArgs();
    }

    public sealed class GetDefaultFirewallParamsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("variant", required: true)]
        public Input<ABKLabs.Svmkit.Firewall.FirewallVariant> Variant { get; set; } = null!;

        public GetDefaultFirewallParamsInvokeArgs()
        {
        }
        public static new GetDefaultFirewallParamsInvokeArgs Empty => new GetDefaultFirewallParamsInvokeArgs();
    }


    [OutputType]
    public sealed class GetDefaultFirewallParamsResult
    {
        public readonly ImmutableArray<string> AllowPorts;
        public readonly ABKLabs.Svmkit.Firewall.FirewallVariant Variant;

        [OutputConstructor]
        private GetDefaultFirewallParamsResult(
            ImmutableArray<string> allowPorts,

            ABKLabs.Svmkit.Firewall.FirewallVariant variant)
        {
            AllowPorts = allowPorts;
            Variant = variant;
        }
    }
}
