// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package tuner

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type CpuGovernor string

const (
	// The performance governor
	CpuGovernorPerformance = CpuGovernor("performance")
	// The powersave governor
	CpuGovernorPowersave = CpuGovernor("powersave")
	// The ondemand governor
	CpuGovernorOndemand = CpuGovernor("ondemand")
	// The conservative governor
	CpuGovernorConservative = CpuGovernor("conservative")
	// The schedutil governor
	CpuGovernorSchedutil = CpuGovernor("schedutil")
	// The userspace governor
	CpuGovernorUserspace = CpuGovernor("userspace")
)

func (CpuGovernor) ElementType() reflect.Type {
	return reflect.TypeOf((*CpuGovernor)(nil)).Elem()
}

func (e CpuGovernor) ToCpuGovernorOutput() CpuGovernorOutput {
	return pulumi.ToOutput(e).(CpuGovernorOutput)
}

func (e CpuGovernor) ToCpuGovernorOutputWithContext(ctx context.Context) CpuGovernorOutput {
	return pulumi.ToOutputWithContext(ctx, e).(CpuGovernorOutput)
}

func (e CpuGovernor) ToCpuGovernorPtrOutput() CpuGovernorPtrOutput {
	return e.ToCpuGovernorPtrOutputWithContext(context.Background())
}

func (e CpuGovernor) ToCpuGovernorPtrOutputWithContext(ctx context.Context) CpuGovernorPtrOutput {
	return CpuGovernor(e).ToCpuGovernorOutputWithContext(ctx).ToCpuGovernorPtrOutputWithContext(ctx)
}

func (e CpuGovernor) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e CpuGovernor) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e CpuGovernor) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e CpuGovernor) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type CpuGovernorOutput struct{ *pulumi.OutputState }

func (CpuGovernorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*CpuGovernor)(nil)).Elem()
}

func (o CpuGovernorOutput) ToCpuGovernorOutput() CpuGovernorOutput {
	return o
}

func (o CpuGovernorOutput) ToCpuGovernorOutputWithContext(ctx context.Context) CpuGovernorOutput {
	return o
}

func (o CpuGovernorOutput) ToCpuGovernorPtrOutput() CpuGovernorPtrOutput {
	return o.ToCpuGovernorPtrOutputWithContext(context.Background())
}

func (o CpuGovernorOutput) ToCpuGovernorPtrOutputWithContext(ctx context.Context) CpuGovernorPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v CpuGovernor) *CpuGovernor {
		return &v
	}).(CpuGovernorPtrOutput)
}

func (o CpuGovernorOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o CpuGovernorOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e CpuGovernor) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o CpuGovernorOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o CpuGovernorOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e CpuGovernor) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type CpuGovernorPtrOutput struct{ *pulumi.OutputState }

func (CpuGovernorPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CpuGovernor)(nil)).Elem()
}

func (o CpuGovernorPtrOutput) ToCpuGovernorPtrOutput() CpuGovernorPtrOutput {
	return o
}

func (o CpuGovernorPtrOutput) ToCpuGovernorPtrOutputWithContext(ctx context.Context) CpuGovernorPtrOutput {
	return o
}

func (o CpuGovernorPtrOutput) Elem() CpuGovernorOutput {
	return o.ApplyT(func(v *CpuGovernor) CpuGovernor {
		if v != nil {
			return *v
		}
		var ret CpuGovernor
		return ret
	}).(CpuGovernorOutput)
}

func (o CpuGovernorPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o CpuGovernorPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *CpuGovernor) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// CpuGovernorInput is an input type that accepts values of the CpuGovernor enum
// A concrete instance of `CpuGovernorInput` can be one of the following:
//
//	CpuGovernorPerformance
//	CpuGovernorPowersave
//	CpuGovernorOndemand
//	CpuGovernorConservative
//	CpuGovernorSchedutil
//	CpuGovernorUserspace
type CpuGovernorInput interface {
	pulumi.Input

	ToCpuGovernorOutput() CpuGovernorOutput
	ToCpuGovernorOutputWithContext(context.Context) CpuGovernorOutput
}

var cpuGovernorPtrType = reflect.TypeOf((**CpuGovernor)(nil)).Elem()

type CpuGovernorPtrInput interface {
	pulumi.Input

	ToCpuGovernorPtrOutput() CpuGovernorPtrOutput
	ToCpuGovernorPtrOutputWithContext(context.Context) CpuGovernorPtrOutput
}

type cpuGovernorPtr string

func CpuGovernorPtr(v string) CpuGovernorPtrInput {
	return (*cpuGovernorPtr)(&v)
}

func (*cpuGovernorPtr) ElementType() reflect.Type {
	return cpuGovernorPtrType
}

func (in *cpuGovernorPtr) ToCpuGovernorPtrOutput() CpuGovernorPtrOutput {
	return pulumi.ToOutput(in).(CpuGovernorPtrOutput)
}

func (in *cpuGovernorPtr) ToCpuGovernorPtrOutputWithContext(ctx context.Context) CpuGovernorPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(CpuGovernorPtrOutput)
}

type TunerVariant string

const (
	// The generic tuner
	TunerVariantGeneric = TunerVariant("generic")
)

func (TunerVariant) ElementType() reflect.Type {
	return reflect.TypeOf((*TunerVariant)(nil)).Elem()
}

func (e TunerVariant) ToTunerVariantOutput() TunerVariantOutput {
	return pulumi.ToOutput(e).(TunerVariantOutput)
}

func (e TunerVariant) ToTunerVariantOutputWithContext(ctx context.Context) TunerVariantOutput {
	return pulumi.ToOutputWithContext(ctx, e).(TunerVariantOutput)
}

func (e TunerVariant) ToTunerVariantPtrOutput() TunerVariantPtrOutput {
	return e.ToTunerVariantPtrOutputWithContext(context.Background())
}

func (e TunerVariant) ToTunerVariantPtrOutputWithContext(ctx context.Context) TunerVariantPtrOutput {
	return TunerVariant(e).ToTunerVariantOutputWithContext(ctx).ToTunerVariantPtrOutputWithContext(ctx)
}

func (e TunerVariant) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e TunerVariant) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e TunerVariant) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e TunerVariant) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type TunerVariantOutput struct{ *pulumi.OutputState }

func (TunerVariantOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TunerVariant)(nil)).Elem()
}

func (o TunerVariantOutput) ToTunerVariantOutput() TunerVariantOutput {
	return o
}

func (o TunerVariantOutput) ToTunerVariantOutputWithContext(ctx context.Context) TunerVariantOutput {
	return o
}

func (o TunerVariantOutput) ToTunerVariantPtrOutput() TunerVariantPtrOutput {
	return o.ToTunerVariantPtrOutputWithContext(context.Background())
}

func (o TunerVariantOutput) ToTunerVariantPtrOutputWithContext(ctx context.Context) TunerVariantPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v TunerVariant) *TunerVariant {
		return &v
	}).(TunerVariantPtrOutput)
}

func (o TunerVariantOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o TunerVariantOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e TunerVariant) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o TunerVariantOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o TunerVariantOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e TunerVariant) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type TunerVariantPtrOutput struct{ *pulumi.OutputState }

func (TunerVariantPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TunerVariant)(nil)).Elem()
}

func (o TunerVariantPtrOutput) ToTunerVariantPtrOutput() TunerVariantPtrOutput {
	return o
}

func (o TunerVariantPtrOutput) ToTunerVariantPtrOutputWithContext(ctx context.Context) TunerVariantPtrOutput {
	return o
}

func (o TunerVariantPtrOutput) Elem() TunerVariantOutput {
	return o.ApplyT(func(v *TunerVariant) TunerVariant {
		if v != nil {
			return *v
		}
		var ret TunerVariant
		return ret
	}).(TunerVariantOutput)
}

func (o TunerVariantPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o TunerVariantPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *TunerVariant) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// TunerVariantInput is an input type that accepts values of the TunerVariant enum
// A concrete instance of `TunerVariantInput` can be one of the following:
//
//	TunerVariantGeneric
type TunerVariantInput interface {
	pulumi.Input

	ToTunerVariantOutput() TunerVariantOutput
	ToTunerVariantOutputWithContext(context.Context) TunerVariantOutput
}

var tunerVariantPtrType = reflect.TypeOf((**TunerVariant)(nil)).Elem()

type TunerVariantPtrInput interface {
	pulumi.Input

	ToTunerVariantPtrOutput() TunerVariantPtrOutput
	ToTunerVariantPtrOutputWithContext(context.Context) TunerVariantPtrOutput
}

type tunerVariantPtr string

func TunerVariantPtr(v string) TunerVariantPtrInput {
	return (*tunerVariantPtr)(&v)
}

func (*tunerVariantPtr) ElementType() reflect.Type {
	return tunerVariantPtrType
}

func (in *tunerVariantPtr) ToTunerVariantPtrOutput() TunerVariantPtrOutput {
	return pulumi.ToOutput(in).(TunerVariantPtrOutput)
}

func (in *tunerVariantPtr) ToTunerVariantPtrOutputWithContext(ctx context.Context) TunerVariantPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(TunerVariantPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CpuGovernorInput)(nil)).Elem(), CpuGovernor("performance"))
	pulumi.RegisterInputType(reflect.TypeOf((*CpuGovernorPtrInput)(nil)).Elem(), CpuGovernor("performance"))
	pulumi.RegisterInputType(reflect.TypeOf((*TunerVariantInput)(nil)).Elem(), TunerVariant("generic"))
	pulumi.RegisterInputType(reflect.TypeOf((*TunerVariantPtrInput)(nil)).Elem(), TunerVariant("generic"))
	pulumi.RegisterOutputType(CpuGovernorOutput{})
	pulumi.RegisterOutputType(CpuGovernorPtrOutput{})
	pulumi.RegisterOutputType(TunerVariantOutput{})
	pulumi.RegisterOutputType(TunerVariantPtrOutput{})
}
