// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package tuner

import (
	"context"
	"reflect"

	"github.com/abklabs/pulumi-svmkit/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type TunerKernelParams struct {
	KernelHungTaskTimeoutSecs      *int `pulumi:"kernelHungTaskTimeoutSecs"`
	KernelNmiWatchdog              *int `pulumi:"kernelNmiWatchdog"`
	KernelPidMax                   *int `pulumi:"kernelPidMax"`
	KernelSchedMinGranularityNs    *int `pulumi:"kernelSchedMinGranularityNs"`
	KernelSchedWakeupGranularityNs *int `pulumi:"kernelSchedWakeupGranularityNs"`
	KernelTimerMigration           *int `pulumi:"kernelTimerMigration"`
}

// TunerKernelParamsInput is an input type that accepts TunerKernelParamsArgs and TunerKernelParamsOutput values.
// You can construct a concrete instance of `TunerKernelParamsInput` via:
//
//	TunerKernelParamsArgs{...}
type TunerKernelParamsInput interface {
	pulumi.Input

	ToTunerKernelParamsOutput() TunerKernelParamsOutput
	ToTunerKernelParamsOutputWithContext(context.Context) TunerKernelParamsOutput
}

type TunerKernelParamsArgs struct {
	KernelHungTaskTimeoutSecs      pulumi.IntPtrInput `pulumi:"kernelHungTaskTimeoutSecs"`
	KernelNmiWatchdog              pulumi.IntPtrInput `pulumi:"kernelNmiWatchdog"`
	KernelPidMax                   pulumi.IntPtrInput `pulumi:"kernelPidMax"`
	KernelSchedMinGranularityNs    pulumi.IntPtrInput `pulumi:"kernelSchedMinGranularityNs"`
	KernelSchedWakeupGranularityNs pulumi.IntPtrInput `pulumi:"kernelSchedWakeupGranularityNs"`
	KernelTimerMigration           pulumi.IntPtrInput `pulumi:"kernelTimerMigration"`
}

func (TunerKernelParamsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TunerKernelParams)(nil)).Elem()
}

func (i TunerKernelParamsArgs) ToTunerKernelParamsOutput() TunerKernelParamsOutput {
	return i.ToTunerKernelParamsOutputWithContext(context.Background())
}

func (i TunerKernelParamsArgs) ToTunerKernelParamsOutputWithContext(ctx context.Context) TunerKernelParamsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TunerKernelParamsOutput)
}

func (i TunerKernelParamsArgs) ToTunerKernelParamsPtrOutput() TunerKernelParamsPtrOutput {
	return i.ToTunerKernelParamsPtrOutputWithContext(context.Background())
}

func (i TunerKernelParamsArgs) ToTunerKernelParamsPtrOutputWithContext(ctx context.Context) TunerKernelParamsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TunerKernelParamsOutput).ToTunerKernelParamsPtrOutputWithContext(ctx)
}

// TunerKernelParamsPtrInput is an input type that accepts TunerKernelParamsArgs, TunerKernelParamsPtr and TunerKernelParamsPtrOutput values.
// You can construct a concrete instance of `TunerKernelParamsPtrInput` via:
//
//	        TunerKernelParamsArgs{...}
//
//	or:
//
//	        nil
type TunerKernelParamsPtrInput interface {
	pulumi.Input

	ToTunerKernelParamsPtrOutput() TunerKernelParamsPtrOutput
	ToTunerKernelParamsPtrOutputWithContext(context.Context) TunerKernelParamsPtrOutput
}

type tunerKernelParamsPtrType TunerKernelParamsArgs

func TunerKernelParamsPtr(v *TunerKernelParamsArgs) TunerKernelParamsPtrInput {
	return (*tunerKernelParamsPtrType)(v)
}

func (*tunerKernelParamsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**TunerKernelParams)(nil)).Elem()
}

func (i *tunerKernelParamsPtrType) ToTunerKernelParamsPtrOutput() TunerKernelParamsPtrOutput {
	return i.ToTunerKernelParamsPtrOutputWithContext(context.Background())
}

func (i *tunerKernelParamsPtrType) ToTunerKernelParamsPtrOutputWithContext(ctx context.Context) TunerKernelParamsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TunerKernelParamsPtrOutput)
}

type TunerKernelParamsOutput struct{ *pulumi.OutputState }

func (TunerKernelParamsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TunerKernelParams)(nil)).Elem()
}

func (o TunerKernelParamsOutput) ToTunerKernelParamsOutput() TunerKernelParamsOutput {
	return o
}

func (o TunerKernelParamsOutput) ToTunerKernelParamsOutputWithContext(ctx context.Context) TunerKernelParamsOutput {
	return o
}

func (o TunerKernelParamsOutput) ToTunerKernelParamsPtrOutput() TunerKernelParamsPtrOutput {
	return o.ToTunerKernelParamsPtrOutputWithContext(context.Background())
}

func (o TunerKernelParamsOutput) ToTunerKernelParamsPtrOutputWithContext(ctx context.Context) TunerKernelParamsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v TunerKernelParams) *TunerKernelParams {
		return &v
	}).(TunerKernelParamsPtrOutput)
}

func (o TunerKernelParamsOutput) KernelHungTaskTimeoutSecs() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerKernelParams) *int { return v.KernelHungTaskTimeoutSecs }).(pulumi.IntPtrOutput)
}

func (o TunerKernelParamsOutput) KernelNmiWatchdog() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerKernelParams) *int { return v.KernelNmiWatchdog }).(pulumi.IntPtrOutput)
}

func (o TunerKernelParamsOutput) KernelPidMax() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerKernelParams) *int { return v.KernelPidMax }).(pulumi.IntPtrOutput)
}

func (o TunerKernelParamsOutput) KernelSchedMinGranularityNs() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerKernelParams) *int { return v.KernelSchedMinGranularityNs }).(pulumi.IntPtrOutput)
}

func (o TunerKernelParamsOutput) KernelSchedWakeupGranularityNs() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerKernelParams) *int { return v.KernelSchedWakeupGranularityNs }).(pulumi.IntPtrOutput)
}

func (o TunerKernelParamsOutput) KernelTimerMigration() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerKernelParams) *int { return v.KernelTimerMigration }).(pulumi.IntPtrOutput)
}

type TunerKernelParamsPtrOutput struct{ *pulumi.OutputState }

func (TunerKernelParamsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TunerKernelParams)(nil)).Elem()
}

func (o TunerKernelParamsPtrOutput) ToTunerKernelParamsPtrOutput() TunerKernelParamsPtrOutput {
	return o
}

func (o TunerKernelParamsPtrOutput) ToTunerKernelParamsPtrOutputWithContext(ctx context.Context) TunerKernelParamsPtrOutput {
	return o
}

func (o TunerKernelParamsPtrOutput) Elem() TunerKernelParamsOutput {
	return o.ApplyT(func(v *TunerKernelParams) TunerKernelParams {
		if v != nil {
			return *v
		}
		var ret TunerKernelParams
		return ret
	}).(TunerKernelParamsOutput)
}

func (o TunerKernelParamsPtrOutput) KernelHungTaskTimeoutSecs() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerKernelParams) *int {
		if v == nil {
			return nil
		}
		return v.KernelHungTaskTimeoutSecs
	}).(pulumi.IntPtrOutput)
}

func (o TunerKernelParamsPtrOutput) KernelNmiWatchdog() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerKernelParams) *int {
		if v == nil {
			return nil
		}
		return v.KernelNmiWatchdog
	}).(pulumi.IntPtrOutput)
}

func (o TunerKernelParamsPtrOutput) KernelPidMax() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerKernelParams) *int {
		if v == nil {
			return nil
		}
		return v.KernelPidMax
	}).(pulumi.IntPtrOutput)
}

func (o TunerKernelParamsPtrOutput) KernelSchedMinGranularityNs() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerKernelParams) *int {
		if v == nil {
			return nil
		}
		return v.KernelSchedMinGranularityNs
	}).(pulumi.IntPtrOutput)
}

func (o TunerKernelParamsPtrOutput) KernelSchedWakeupGranularityNs() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerKernelParams) *int {
		if v == nil {
			return nil
		}
		return v.KernelSchedWakeupGranularityNs
	}).(pulumi.IntPtrOutput)
}

func (o TunerKernelParamsPtrOutput) KernelTimerMigration() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerKernelParams) *int {
		if v == nil {
			return nil
		}
		return v.KernelTimerMigration
	}).(pulumi.IntPtrOutput)
}

type TunerNetParams struct {
	NetCoreRmemDefault          *int    `pulumi:"netCoreRmemDefault"`
	NetCoreRmemMax              *int    `pulumi:"netCoreRmemMax"`
	NetCoreWmemDefault          *int    `pulumi:"netCoreWmemDefault"`
	NetCoreWmemMax              *int    `pulumi:"netCoreWmemMax"`
	NetIpv4TcpCongestionControl *string `pulumi:"netIpv4TcpCongestionControl"`
	NetIpv4TcpFastopen          *int    `pulumi:"netIpv4TcpFastopen"`
	NetIpv4TcpLowLatency        *int    `pulumi:"netIpv4TcpLowLatency"`
	NetIpv4TcpModerateRcvbuf    *int    `pulumi:"netIpv4TcpModerateRcvbuf"`
	NetIpv4TcpNoMetricsSave     *int    `pulumi:"netIpv4TcpNoMetricsSave"`
	NetIpv4TcpRmem              *string `pulumi:"netIpv4TcpRmem"`
	NetIpv4TcpSack              *int    `pulumi:"netIpv4TcpSack"`
	NetIpv4TcpTimestamps        *int    `pulumi:"netIpv4TcpTimestamps"`
	NetIpv4TcpTwReuse           *int    `pulumi:"netIpv4TcpTwReuse"`
	NetIpv4TcpWmem              *string `pulumi:"netIpv4TcpWmem"`
}

// TunerNetParamsInput is an input type that accepts TunerNetParamsArgs and TunerNetParamsOutput values.
// You can construct a concrete instance of `TunerNetParamsInput` via:
//
//	TunerNetParamsArgs{...}
type TunerNetParamsInput interface {
	pulumi.Input

	ToTunerNetParamsOutput() TunerNetParamsOutput
	ToTunerNetParamsOutputWithContext(context.Context) TunerNetParamsOutput
}

type TunerNetParamsArgs struct {
	NetCoreRmemDefault          pulumi.IntPtrInput    `pulumi:"netCoreRmemDefault"`
	NetCoreRmemMax              pulumi.IntPtrInput    `pulumi:"netCoreRmemMax"`
	NetCoreWmemDefault          pulumi.IntPtrInput    `pulumi:"netCoreWmemDefault"`
	NetCoreWmemMax              pulumi.IntPtrInput    `pulumi:"netCoreWmemMax"`
	NetIpv4TcpCongestionControl pulumi.StringPtrInput `pulumi:"netIpv4TcpCongestionControl"`
	NetIpv4TcpFastopen          pulumi.IntPtrInput    `pulumi:"netIpv4TcpFastopen"`
	NetIpv4TcpLowLatency        pulumi.IntPtrInput    `pulumi:"netIpv4TcpLowLatency"`
	NetIpv4TcpModerateRcvbuf    pulumi.IntPtrInput    `pulumi:"netIpv4TcpModerateRcvbuf"`
	NetIpv4TcpNoMetricsSave     pulumi.IntPtrInput    `pulumi:"netIpv4TcpNoMetricsSave"`
	NetIpv4TcpRmem              pulumi.StringPtrInput `pulumi:"netIpv4TcpRmem"`
	NetIpv4TcpSack              pulumi.IntPtrInput    `pulumi:"netIpv4TcpSack"`
	NetIpv4TcpTimestamps        pulumi.IntPtrInput    `pulumi:"netIpv4TcpTimestamps"`
	NetIpv4TcpTwReuse           pulumi.IntPtrInput    `pulumi:"netIpv4TcpTwReuse"`
	NetIpv4TcpWmem              pulumi.StringPtrInput `pulumi:"netIpv4TcpWmem"`
}

func (TunerNetParamsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TunerNetParams)(nil)).Elem()
}

func (i TunerNetParamsArgs) ToTunerNetParamsOutput() TunerNetParamsOutput {
	return i.ToTunerNetParamsOutputWithContext(context.Background())
}

func (i TunerNetParamsArgs) ToTunerNetParamsOutputWithContext(ctx context.Context) TunerNetParamsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TunerNetParamsOutput)
}

func (i TunerNetParamsArgs) ToTunerNetParamsPtrOutput() TunerNetParamsPtrOutput {
	return i.ToTunerNetParamsPtrOutputWithContext(context.Background())
}

func (i TunerNetParamsArgs) ToTunerNetParamsPtrOutputWithContext(ctx context.Context) TunerNetParamsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TunerNetParamsOutput).ToTunerNetParamsPtrOutputWithContext(ctx)
}

// TunerNetParamsPtrInput is an input type that accepts TunerNetParamsArgs, TunerNetParamsPtr and TunerNetParamsPtrOutput values.
// You can construct a concrete instance of `TunerNetParamsPtrInput` via:
//
//	        TunerNetParamsArgs{...}
//
//	or:
//
//	        nil
type TunerNetParamsPtrInput interface {
	pulumi.Input

	ToTunerNetParamsPtrOutput() TunerNetParamsPtrOutput
	ToTunerNetParamsPtrOutputWithContext(context.Context) TunerNetParamsPtrOutput
}

type tunerNetParamsPtrType TunerNetParamsArgs

func TunerNetParamsPtr(v *TunerNetParamsArgs) TunerNetParamsPtrInput {
	return (*tunerNetParamsPtrType)(v)
}

func (*tunerNetParamsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**TunerNetParams)(nil)).Elem()
}

func (i *tunerNetParamsPtrType) ToTunerNetParamsPtrOutput() TunerNetParamsPtrOutput {
	return i.ToTunerNetParamsPtrOutputWithContext(context.Background())
}

func (i *tunerNetParamsPtrType) ToTunerNetParamsPtrOutputWithContext(ctx context.Context) TunerNetParamsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TunerNetParamsPtrOutput)
}

type TunerNetParamsOutput struct{ *pulumi.OutputState }

func (TunerNetParamsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TunerNetParams)(nil)).Elem()
}

func (o TunerNetParamsOutput) ToTunerNetParamsOutput() TunerNetParamsOutput {
	return o
}

func (o TunerNetParamsOutput) ToTunerNetParamsOutputWithContext(ctx context.Context) TunerNetParamsOutput {
	return o
}

func (o TunerNetParamsOutput) ToTunerNetParamsPtrOutput() TunerNetParamsPtrOutput {
	return o.ToTunerNetParamsPtrOutputWithContext(context.Background())
}

func (o TunerNetParamsOutput) ToTunerNetParamsPtrOutputWithContext(ctx context.Context) TunerNetParamsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v TunerNetParams) *TunerNetParams {
		return &v
	}).(TunerNetParamsPtrOutput)
}

func (o TunerNetParamsOutput) NetCoreRmemDefault() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerNetParams) *int { return v.NetCoreRmemDefault }).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsOutput) NetCoreRmemMax() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerNetParams) *int { return v.NetCoreRmemMax }).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsOutput) NetCoreWmemDefault() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerNetParams) *int { return v.NetCoreWmemDefault }).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsOutput) NetCoreWmemMax() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerNetParams) *int { return v.NetCoreWmemMax }).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsOutput) NetIpv4TcpCongestionControl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TunerNetParams) *string { return v.NetIpv4TcpCongestionControl }).(pulumi.StringPtrOutput)
}

func (o TunerNetParamsOutput) NetIpv4TcpFastopen() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerNetParams) *int { return v.NetIpv4TcpFastopen }).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsOutput) NetIpv4TcpLowLatency() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerNetParams) *int { return v.NetIpv4TcpLowLatency }).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsOutput) NetIpv4TcpModerateRcvbuf() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerNetParams) *int { return v.NetIpv4TcpModerateRcvbuf }).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsOutput) NetIpv4TcpNoMetricsSave() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerNetParams) *int { return v.NetIpv4TcpNoMetricsSave }).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsOutput) NetIpv4TcpRmem() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TunerNetParams) *string { return v.NetIpv4TcpRmem }).(pulumi.StringPtrOutput)
}

func (o TunerNetParamsOutput) NetIpv4TcpSack() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerNetParams) *int { return v.NetIpv4TcpSack }).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsOutput) NetIpv4TcpTimestamps() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerNetParams) *int { return v.NetIpv4TcpTimestamps }).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsOutput) NetIpv4TcpTwReuse() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerNetParams) *int { return v.NetIpv4TcpTwReuse }).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsOutput) NetIpv4TcpWmem() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TunerNetParams) *string { return v.NetIpv4TcpWmem }).(pulumi.StringPtrOutput)
}

type TunerNetParamsPtrOutput struct{ *pulumi.OutputState }

func (TunerNetParamsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TunerNetParams)(nil)).Elem()
}

func (o TunerNetParamsPtrOutput) ToTunerNetParamsPtrOutput() TunerNetParamsPtrOutput {
	return o
}

func (o TunerNetParamsPtrOutput) ToTunerNetParamsPtrOutputWithContext(ctx context.Context) TunerNetParamsPtrOutput {
	return o
}

func (o TunerNetParamsPtrOutput) Elem() TunerNetParamsOutput {
	return o.ApplyT(func(v *TunerNetParams) TunerNetParams {
		if v != nil {
			return *v
		}
		var ret TunerNetParams
		return ret
	}).(TunerNetParamsOutput)
}

func (o TunerNetParamsPtrOutput) NetCoreRmemDefault() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerNetParams) *int {
		if v == nil {
			return nil
		}
		return v.NetCoreRmemDefault
	}).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsPtrOutput) NetCoreRmemMax() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerNetParams) *int {
		if v == nil {
			return nil
		}
		return v.NetCoreRmemMax
	}).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsPtrOutput) NetCoreWmemDefault() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerNetParams) *int {
		if v == nil {
			return nil
		}
		return v.NetCoreWmemDefault
	}).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsPtrOutput) NetCoreWmemMax() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerNetParams) *int {
		if v == nil {
			return nil
		}
		return v.NetCoreWmemMax
	}).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsPtrOutput) NetIpv4TcpCongestionControl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TunerNetParams) *string {
		if v == nil {
			return nil
		}
		return v.NetIpv4TcpCongestionControl
	}).(pulumi.StringPtrOutput)
}

func (o TunerNetParamsPtrOutput) NetIpv4TcpFastopen() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerNetParams) *int {
		if v == nil {
			return nil
		}
		return v.NetIpv4TcpFastopen
	}).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsPtrOutput) NetIpv4TcpLowLatency() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerNetParams) *int {
		if v == nil {
			return nil
		}
		return v.NetIpv4TcpLowLatency
	}).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsPtrOutput) NetIpv4TcpModerateRcvbuf() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerNetParams) *int {
		if v == nil {
			return nil
		}
		return v.NetIpv4TcpModerateRcvbuf
	}).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsPtrOutput) NetIpv4TcpNoMetricsSave() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerNetParams) *int {
		if v == nil {
			return nil
		}
		return v.NetIpv4TcpNoMetricsSave
	}).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsPtrOutput) NetIpv4TcpRmem() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TunerNetParams) *string {
		if v == nil {
			return nil
		}
		return v.NetIpv4TcpRmem
	}).(pulumi.StringPtrOutput)
}

func (o TunerNetParamsPtrOutput) NetIpv4TcpSack() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerNetParams) *int {
		if v == nil {
			return nil
		}
		return v.NetIpv4TcpSack
	}).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsPtrOutput) NetIpv4TcpTimestamps() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerNetParams) *int {
		if v == nil {
			return nil
		}
		return v.NetIpv4TcpTimestamps
	}).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsPtrOutput) NetIpv4TcpTwReuse() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerNetParams) *int {
		if v == nil {
			return nil
		}
		return v.NetIpv4TcpTwReuse
	}).(pulumi.IntPtrOutput)
}

func (o TunerNetParamsPtrOutput) NetIpv4TcpWmem() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TunerNetParams) *string {
		if v == nil {
			return nil
		}
		return v.NetIpv4TcpWmem
	}).(pulumi.StringPtrOutput)
}

type TunerParams struct {
	CpuGovernor *CpuGovernor       `pulumi:"cpuGovernor"`
	Kernel      *TunerKernelParams `pulumi:"kernel"`
	Net         *TunerNetParams    `pulumi:"net"`
	Vm          *TunerVmParams     `pulumi:"vm"`
}

// TunerParamsInput is an input type that accepts TunerParamsArgs and TunerParamsOutput values.
// You can construct a concrete instance of `TunerParamsInput` via:
//
//	TunerParamsArgs{...}
type TunerParamsInput interface {
	pulumi.Input

	ToTunerParamsOutput() TunerParamsOutput
	ToTunerParamsOutputWithContext(context.Context) TunerParamsOutput
}

type TunerParamsArgs struct {
	CpuGovernor CpuGovernorPtrInput       `pulumi:"cpuGovernor"`
	Kernel      TunerKernelParamsPtrInput `pulumi:"kernel"`
	Net         TunerNetParamsPtrInput    `pulumi:"net"`
	Vm          TunerVmParamsPtrInput     `pulumi:"vm"`
}

func (TunerParamsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TunerParams)(nil)).Elem()
}

func (i TunerParamsArgs) ToTunerParamsOutput() TunerParamsOutput {
	return i.ToTunerParamsOutputWithContext(context.Background())
}

func (i TunerParamsArgs) ToTunerParamsOutputWithContext(ctx context.Context) TunerParamsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TunerParamsOutput)
}

type TunerParamsOutput struct{ *pulumi.OutputState }

func (TunerParamsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TunerParams)(nil)).Elem()
}

func (o TunerParamsOutput) ToTunerParamsOutput() TunerParamsOutput {
	return o
}

func (o TunerParamsOutput) ToTunerParamsOutputWithContext(ctx context.Context) TunerParamsOutput {
	return o
}

func (o TunerParamsOutput) CpuGovernor() CpuGovernorPtrOutput {
	return o.ApplyT(func(v TunerParams) *CpuGovernor { return v.CpuGovernor }).(CpuGovernorPtrOutput)
}

func (o TunerParamsOutput) Kernel() TunerKernelParamsPtrOutput {
	return o.ApplyT(func(v TunerParams) *TunerKernelParams { return v.Kernel }).(TunerKernelParamsPtrOutput)
}

func (o TunerParamsOutput) Net() TunerNetParamsPtrOutput {
	return o.ApplyT(func(v TunerParams) *TunerNetParams { return v.Net }).(TunerNetParamsPtrOutput)
}

func (o TunerParamsOutput) Vm() TunerVmParamsPtrOutput {
	return o.ApplyT(func(v TunerParams) *TunerVmParams { return v.Vm }).(TunerVmParamsPtrOutput)
}

type TunerVmParams struct {
	VmDirtyBackgroundRatio    *int `pulumi:"vmDirtyBackgroundRatio"`
	VmDirtyExpireCentisecs    *int `pulumi:"vmDirtyExpireCentisecs"`
	VmDirtyRatio              *int `pulumi:"vmDirtyRatio"`
	VmDirtyWritebackCentisecs *int `pulumi:"vmDirtyWritebackCentisecs"`
	VmDirtytimeExpireSeconds  *int `pulumi:"vmDirtytimeExpireSeconds"`
	VmMaxMapCount             *int `pulumi:"vmMaxMapCount"`
	VmMinFreeKbytes           *int `pulumi:"vmMinFreeKbytes"`
	VmStatInterval            *int `pulumi:"vmStatInterval"`
	VmSwappiness              *int `pulumi:"vmSwappiness"`
}

// TunerVmParamsInput is an input type that accepts TunerVmParamsArgs and TunerVmParamsOutput values.
// You can construct a concrete instance of `TunerVmParamsInput` via:
//
//	TunerVmParamsArgs{...}
type TunerVmParamsInput interface {
	pulumi.Input

	ToTunerVmParamsOutput() TunerVmParamsOutput
	ToTunerVmParamsOutputWithContext(context.Context) TunerVmParamsOutput
}

type TunerVmParamsArgs struct {
	VmDirtyBackgroundRatio    pulumi.IntPtrInput `pulumi:"vmDirtyBackgroundRatio"`
	VmDirtyExpireCentisecs    pulumi.IntPtrInput `pulumi:"vmDirtyExpireCentisecs"`
	VmDirtyRatio              pulumi.IntPtrInput `pulumi:"vmDirtyRatio"`
	VmDirtyWritebackCentisecs pulumi.IntPtrInput `pulumi:"vmDirtyWritebackCentisecs"`
	VmDirtytimeExpireSeconds  pulumi.IntPtrInput `pulumi:"vmDirtytimeExpireSeconds"`
	VmMaxMapCount             pulumi.IntPtrInput `pulumi:"vmMaxMapCount"`
	VmMinFreeKbytes           pulumi.IntPtrInput `pulumi:"vmMinFreeKbytes"`
	VmStatInterval            pulumi.IntPtrInput `pulumi:"vmStatInterval"`
	VmSwappiness              pulumi.IntPtrInput `pulumi:"vmSwappiness"`
}

func (TunerVmParamsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TunerVmParams)(nil)).Elem()
}

func (i TunerVmParamsArgs) ToTunerVmParamsOutput() TunerVmParamsOutput {
	return i.ToTunerVmParamsOutputWithContext(context.Background())
}

func (i TunerVmParamsArgs) ToTunerVmParamsOutputWithContext(ctx context.Context) TunerVmParamsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TunerVmParamsOutput)
}

func (i TunerVmParamsArgs) ToTunerVmParamsPtrOutput() TunerVmParamsPtrOutput {
	return i.ToTunerVmParamsPtrOutputWithContext(context.Background())
}

func (i TunerVmParamsArgs) ToTunerVmParamsPtrOutputWithContext(ctx context.Context) TunerVmParamsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TunerVmParamsOutput).ToTunerVmParamsPtrOutputWithContext(ctx)
}

// TunerVmParamsPtrInput is an input type that accepts TunerVmParamsArgs, TunerVmParamsPtr and TunerVmParamsPtrOutput values.
// You can construct a concrete instance of `TunerVmParamsPtrInput` via:
//
//	        TunerVmParamsArgs{...}
//
//	or:
//
//	        nil
type TunerVmParamsPtrInput interface {
	pulumi.Input

	ToTunerVmParamsPtrOutput() TunerVmParamsPtrOutput
	ToTunerVmParamsPtrOutputWithContext(context.Context) TunerVmParamsPtrOutput
}

type tunerVmParamsPtrType TunerVmParamsArgs

func TunerVmParamsPtr(v *TunerVmParamsArgs) TunerVmParamsPtrInput {
	return (*tunerVmParamsPtrType)(v)
}

func (*tunerVmParamsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**TunerVmParams)(nil)).Elem()
}

func (i *tunerVmParamsPtrType) ToTunerVmParamsPtrOutput() TunerVmParamsPtrOutput {
	return i.ToTunerVmParamsPtrOutputWithContext(context.Background())
}

func (i *tunerVmParamsPtrType) ToTunerVmParamsPtrOutputWithContext(ctx context.Context) TunerVmParamsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TunerVmParamsPtrOutput)
}

type TunerVmParamsOutput struct{ *pulumi.OutputState }

func (TunerVmParamsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TunerVmParams)(nil)).Elem()
}

func (o TunerVmParamsOutput) ToTunerVmParamsOutput() TunerVmParamsOutput {
	return o
}

func (o TunerVmParamsOutput) ToTunerVmParamsOutputWithContext(ctx context.Context) TunerVmParamsOutput {
	return o
}

func (o TunerVmParamsOutput) ToTunerVmParamsPtrOutput() TunerVmParamsPtrOutput {
	return o.ToTunerVmParamsPtrOutputWithContext(context.Background())
}

func (o TunerVmParamsOutput) ToTunerVmParamsPtrOutputWithContext(ctx context.Context) TunerVmParamsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v TunerVmParams) *TunerVmParams {
		return &v
	}).(TunerVmParamsPtrOutput)
}

func (o TunerVmParamsOutput) VmDirtyBackgroundRatio() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerVmParams) *int { return v.VmDirtyBackgroundRatio }).(pulumi.IntPtrOutput)
}

func (o TunerVmParamsOutput) VmDirtyExpireCentisecs() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerVmParams) *int { return v.VmDirtyExpireCentisecs }).(pulumi.IntPtrOutput)
}

func (o TunerVmParamsOutput) VmDirtyRatio() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerVmParams) *int { return v.VmDirtyRatio }).(pulumi.IntPtrOutput)
}

func (o TunerVmParamsOutput) VmDirtyWritebackCentisecs() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerVmParams) *int { return v.VmDirtyWritebackCentisecs }).(pulumi.IntPtrOutput)
}

func (o TunerVmParamsOutput) VmDirtytimeExpireSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerVmParams) *int { return v.VmDirtytimeExpireSeconds }).(pulumi.IntPtrOutput)
}

func (o TunerVmParamsOutput) VmMaxMapCount() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerVmParams) *int { return v.VmMaxMapCount }).(pulumi.IntPtrOutput)
}

func (o TunerVmParamsOutput) VmMinFreeKbytes() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerVmParams) *int { return v.VmMinFreeKbytes }).(pulumi.IntPtrOutput)
}

func (o TunerVmParamsOutput) VmStatInterval() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerVmParams) *int { return v.VmStatInterval }).(pulumi.IntPtrOutput)
}

func (o TunerVmParamsOutput) VmSwappiness() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TunerVmParams) *int { return v.VmSwappiness }).(pulumi.IntPtrOutput)
}

type TunerVmParamsPtrOutput struct{ *pulumi.OutputState }

func (TunerVmParamsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TunerVmParams)(nil)).Elem()
}

func (o TunerVmParamsPtrOutput) ToTunerVmParamsPtrOutput() TunerVmParamsPtrOutput {
	return o
}

func (o TunerVmParamsPtrOutput) ToTunerVmParamsPtrOutputWithContext(ctx context.Context) TunerVmParamsPtrOutput {
	return o
}

func (o TunerVmParamsPtrOutput) Elem() TunerVmParamsOutput {
	return o.ApplyT(func(v *TunerVmParams) TunerVmParams {
		if v != nil {
			return *v
		}
		var ret TunerVmParams
		return ret
	}).(TunerVmParamsOutput)
}

func (o TunerVmParamsPtrOutput) VmDirtyBackgroundRatio() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerVmParams) *int {
		if v == nil {
			return nil
		}
		return v.VmDirtyBackgroundRatio
	}).(pulumi.IntPtrOutput)
}

func (o TunerVmParamsPtrOutput) VmDirtyExpireCentisecs() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerVmParams) *int {
		if v == nil {
			return nil
		}
		return v.VmDirtyExpireCentisecs
	}).(pulumi.IntPtrOutput)
}

func (o TunerVmParamsPtrOutput) VmDirtyRatio() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerVmParams) *int {
		if v == nil {
			return nil
		}
		return v.VmDirtyRatio
	}).(pulumi.IntPtrOutput)
}

func (o TunerVmParamsPtrOutput) VmDirtyWritebackCentisecs() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerVmParams) *int {
		if v == nil {
			return nil
		}
		return v.VmDirtyWritebackCentisecs
	}).(pulumi.IntPtrOutput)
}

func (o TunerVmParamsPtrOutput) VmDirtytimeExpireSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerVmParams) *int {
		if v == nil {
			return nil
		}
		return v.VmDirtytimeExpireSeconds
	}).(pulumi.IntPtrOutput)
}

func (o TunerVmParamsPtrOutput) VmMaxMapCount() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerVmParams) *int {
		if v == nil {
			return nil
		}
		return v.VmMaxMapCount
	}).(pulumi.IntPtrOutput)
}

func (o TunerVmParamsPtrOutput) VmMinFreeKbytes() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerVmParams) *int {
		if v == nil {
			return nil
		}
		return v.VmMinFreeKbytes
	}).(pulumi.IntPtrOutput)
}

func (o TunerVmParamsPtrOutput) VmStatInterval() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerVmParams) *int {
		if v == nil {
			return nil
		}
		return v.VmStatInterval
	}).(pulumi.IntPtrOutput)
}

func (o TunerVmParamsPtrOutput) VmSwappiness() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TunerVmParams) *int {
		if v == nil {
			return nil
		}
		return v.VmSwappiness
	}).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TunerKernelParamsInput)(nil)).Elem(), TunerKernelParamsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TunerKernelParamsPtrInput)(nil)).Elem(), TunerKernelParamsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TunerNetParamsInput)(nil)).Elem(), TunerNetParamsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TunerNetParamsPtrInput)(nil)).Elem(), TunerNetParamsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TunerParamsInput)(nil)).Elem(), TunerParamsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TunerVmParamsInput)(nil)).Elem(), TunerVmParamsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TunerVmParamsPtrInput)(nil)).Elem(), TunerVmParamsArgs{})
	pulumi.RegisterOutputType(TunerKernelParamsOutput{})
	pulumi.RegisterOutputType(TunerKernelParamsPtrOutput{})
	pulumi.RegisterOutputType(TunerNetParamsOutput{})
	pulumi.RegisterOutputType(TunerNetParamsPtrOutput{})
	pulumi.RegisterOutputType(TunerParamsOutput{})
	pulumi.RegisterOutputType(TunerVmParamsOutput{})
	pulumi.RegisterOutputType(TunerVmParamsPtrOutput{})
}
