// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const NetworkName = {
    /**
     * Solana devnet
     */
    Devnet: "devnet",
    /**
     * Solana testnet
     */
    Testnet: "testnet",
    /**
     * Solana mainnet-beta
     */
    Mainnet_beta: "mainnet-beta",
} as const;

export type NetworkName = (typeof NetworkName)[keyof typeof NetworkName];
