// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Svmkit.Firewall.Inputs
{

    public sealed class FirewallParamsArgs : global::Pulumi.ResourceArgs
    {
        [Input("allowPorts", required: true)]
        private InputList<string>? _allowPorts;
        public InputList<string> AllowPorts
        {
            get => _allowPorts ?? (_allowPorts = new InputList<string>());
            set => _allowPorts = value;
        }

        public FirewallParamsArgs()
        {
        }
        public static new FirewallParamsArgs Empty => new FirewallParamsArgs();
    }
}
