// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package firewall

import (
	"context"
	"reflect"

	"github.com/abklabs/pulumi-svmkit/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDefaultFirewallParams(ctx *pulumi.Context, args *GetDefaultFirewallParamsArgs, opts ...pulumi.InvokeOption) (*GetDefaultFirewallParamsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDefaultFirewallParamsResult
	err := ctx.Invoke("svmkit:firewall:getDefaultFirewallParams", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetDefaultFirewallParamsArgs struct {
	Variant FirewallVariant `pulumi:"variant"`
}

type GetDefaultFirewallParamsResult struct {
	AllowPorts []string        `pulumi:"allowPorts"`
	Variant    FirewallVariant `pulumi:"variant"`
}

func GetDefaultFirewallParamsOutput(ctx *pulumi.Context, args GetDefaultFirewallParamsOutputArgs, opts ...pulumi.InvokeOption) GetDefaultFirewallParamsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetDefaultFirewallParamsResultOutput, error) {
			args := v.(GetDefaultFirewallParamsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("svmkit:firewall:getDefaultFirewallParams", args, GetDefaultFirewallParamsResultOutput{}, options).(GetDefaultFirewallParamsResultOutput), nil
		}).(GetDefaultFirewallParamsResultOutput)
}

type GetDefaultFirewallParamsOutputArgs struct {
	Variant FirewallVariantInput `pulumi:"variant"`
}

func (GetDefaultFirewallParamsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDefaultFirewallParamsArgs)(nil)).Elem()
}

type GetDefaultFirewallParamsResultOutput struct{ *pulumi.OutputState }

func (GetDefaultFirewallParamsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDefaultFirewallParamsResult)(nil)).Elem()
}

func (o GetDefaultFirewallParamsResultOutput) ToGetDefaultFirewallParamsResultOutput() GetDefaultFirewallParamsResultOutput {
	return o
}

func (o GetDefaultFirewallParamsResultOutput) ToGetDefaultFirewallParamsResultOutputWithContext(ctx context.Context) GetDefaultFirewallParamsResultOutput {
	return o
}

func (o GetDefaultFirewallParamsResultOutput) AllowPorts() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetDefaultFirewallParamsResult) []string { return v.AllowPorts }).(pulumi.StringArrayOutput)
}

func (o GetDefaultFirewallParamsResultOutput) Variant() FirewallVariantOutput {
	return o.ApplyT(func(v GetDefaultFirewallParamsResult) FirewallVariant { return v.Variant }).(FirewallVariantOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDefaultFirewallParamsResultOutput{})
}
