// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package firewall

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type FirewallVariant string

const (
	// The generic firewall
	FirewallVariantGeneric = FirewallVariant("generic")
)

func (FirewallVariant) ElementType() reflect.Type {
	return reflect.TypeOf((*FirewallVariant)(nil)).Elem()
}

func (e FirewallVariant) ToFirewallVariantOutput() FirewallVariantOutput {
	return pulumi.ToOutput(e).(FirewallVariantOutput)
}

func (e FirewallVariant) ToFirewallVariantOutputWithContext(ctx context.Context) FirewallVariantOutput {
	return pulumi.ToOutputWithContext(ctx, e).(FirewallVariantOutput)
}

func (e FirewallVariant) ToFirewallVariantPtrOutput() FirewallVariantPtrOutput {
	return e.ToFirewallVariantPtrOutputWithContext(context.Background())
}

func (e FirewallVariant) ToFirewallVariantPtrOutputWithContext(ctx context.Context) FirewallVariantPtrOutput {
	return FirewallVariant(e).ToFirewallVariantOutputWithContext(ctx).ToFirewallVariantPtrOutputWithContext(ctx)
}

func (e FirewallVariant) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e FirewallVariant) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e FirewallVariant) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e FirewallVariant) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type FirewallVariantOutput struct{ *pulumi.OutputState }

func (FirewallVariantOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*FirewallVariant)(nil)).Elem()
}

func (o FirewallVariantOutput) ToFirewallVariantOutput() FirewallVariantOutput {
	return o
}

func (o FirewallVariantOutput) ToFirewallVariantOutputWithContext(ctx context.Context) FirewallVariantOutput {
	return o
}

func (o FirewallVariantOutput) ToFirewallVariantPtrOutput() FirewallVariantPtrOutput {
	return o.ToFirewallVariantPtrOutputWithContext(context.Background())
}

func (o FirewallVariantOutput) ToFirewallVariantPtrOutputWithContext(ctx context.Context) FirewallVariantPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v FirewallVariant) *FirewallVariant {
		return &v
	}).(FirewallVariantPtrOutput)
}

func (o FirewallVariantOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o FirewallVariantOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e FirewallVariant) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o FirewallVariantOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o FirewallVariantOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e FirewallVariant) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type FirewallVariantPtrOutput struct{ *pulumi.OutputState }

func (FirewallVariantPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FirewallVariant)(nil)).Elem()
}

func (o FirewallVariantPtrOutput) ToFirewallVariantPtrOutput() FirewallVariantPtrOutput {
	return o
}

func (o FirewallVariantPtrOutput) ToFirewallVariantPtrOutputWithContext(ctx context.Context) FirewallVariantPtrOutput {
	return o
}

func (o FirewallVariantPtrOutput) Elem() FirewallVariantOutput {
	return o.ApplyT(func(v *FirewallVariant) FirewallVariant {
		if v != nil {
			return *v
		}
		var ret FirewallVariant
		return ret
	}).(FirewallVariantOutput)
}

func (o FirewallVariantPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o FirewallVariantPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *FirewallVariant) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// FirewallVariantInput is an input type that accepts values of the FirewallVariant enum
// A concrete instance of `FirewallVariantInput` can be one of the following:
//
//	FirewallVariantGeneric
type FirewallVariantInput interface {
	pulumi.Input

	ToFirewallVariantOutput() FirewallVariantOutput
	ToFirewallVariantOutputWithContext(context.Context) FirewallVariantOutput
}

var firewallVariantPtrType = reflect.TypeOf((**FirewallVariant)(nil)).Elem()

type FirewallVariantPtrInput interface {
	pulumi.Input

	ToFirewallVariantPtrOutput() FirewallVariantPtrOutput
	ToFirewallVariantPtrOutputWithContext(context.Context) FirewallVariantPtrOutput
}

type firewallVariantPtr string

func FirewallVariantPtr(v string) FirewallVariantPtrInput {
	return (*firewallVariantPtr)(&v)
}

func (*firewallVariantPtr) ElementType() reflect.Type {
	return firewallVariantPtrType
}

func (in *firewallVariantPtr) ToFirewallVariantPtrOutput() FirewallVariantPtrOutput {
	return pulumi.ToOutput(in).(FirewallVariantPtrOutput)
}

func (in *firewallVariantPtr) ToFirewallVariantPtrOutputWithContext(ctx context.Context) FirewallVariantPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(FirewallVariantPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FirewallVariantInput)(nil)).Elem(), FirewallVariant("generic"))
	pulumi.RegisterInputType(reflect.TypeOf((*FirewallVariantPtrInput)(nil)).Elem(), FirewallVariant("generic"))
	pulumi.RegisterOutputType(FirewallVariantOutput{})
	pulumi.RegisterOutputType(FirewallVariantPtrOutput{})
}
