// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package firewall

import (
	"context"
	"reflect"

	"github.com/abklabs/pulumi-svmkit/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type FirewallParams struct {
	AllowPorts []string `pulumi:"allowPorts"`
}

// FirewallParamsInput is an input type that accepts FirewallParamsArgs and FirewallParamsOutput values.
// You can construct a concrete instance of `FirewallParamsInput` via:
//
//	FirewallParamsArgs{...}
type FirewallParamsInput interface {
	pulumi.Input

	ToFirewallParamsOutput() FirewallParamsOutput
	ToFirewallParamsOutputWithContext(context.Context) FirewallParamsOutput
}

type FirewallParamsArgs struct {
	AllowPorts pulumi.StringArrayInput `pulumi:"allowPorts"`
}

func (FirewallParamsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*FirewallParams)(nil)).Elem()
}

func (i FirewallParamsArgs) ToFirewallParamsOutput() FirewallParamsOutput {
	return i.ToFirewallParamsOutputWithContext(context.Background())
}

func (i FirewallParamsArgs) ToFirewallParamsOutputWithContext(ctx context.Context) FirewallParamsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FirewallParamsOutput)
}

type FirewallParamsOutput struct{ *pulumi.OutputState }

func (FirewallParamsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*FirewallParams)(nil)).Elem()
}

func (o FirewallParamsOutput) ToFirewallParamsOutput() FirewallParamsOutput {
	return o
}

func (o FirewallParamsOutput) ToFirewallParamsOutputWithContext(ctx context.Context) FirewallParamsOutput {
	return o
}

func (o FirewallParamsOutput) AllowPorts() pulumi.StringArrayOutput {
	return o.ApplyT(func(v FirewallParams) []string { return v.AllowPorts }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FirewallParamsInput)(nil)).Elem(), FirewallParamsArgs{})
	pulumi.RegisterOutputType(FirewallParamsOutput{})
}
